# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib jsslintr, .registration = TRUE
NULL

#' Lint files against the JSS style guide
#'
#' Mirrors `jsslint::render` (the PyO3 binding) / the WASM binding's
#' `render()`.
#' @param files A named character vector: names are file paths
#'   (`.tex`/`.ltx`/`.bib`/`.Rnw`/`.Rmd`), values are the file contents.
#' @param journal Journal identifier (default: `"jss"`).
#' @param mode `"author"` or `"reviewer"` (default: `"author"`).
#' @param output `"terminal"`, `"json"`, `"sarif"`, or `"html"`
#'   (default: `"terminal"`).
#' @param ignore_rules Comma-separated rule ids to suppress.
#' @param min_confidence `"low"`, `"medium"`, or `"high"`.
#' @param fail_on `"error"`, `"warning"`, or `"info"`.
#' @param source_root Base directory for SARIF artifact URIs.
#' @param verbose Enable diagnostic output on stderr.
#' @return The rendered report, as a single string.
#' @export
render <- function(files, journal = NULL, mode = NULL, output = NULL, ignore_rules = NULL, min_confidence = NULL, fail_on = NULL, source_root = NULL, verbose = NULL) .Call(wrap__render, files, journal, mode, output, ignore_rules, min_confidence, fail_on, source_root, verbose)

#' Structured lint results backing `jsslint()` — internal; the
#' user-facing wrapper turns the parallel vectors into data frames.
#' @noRd
lint_data <- function(files, journal = NULL, mode = NULL, ignore_rules = NULL, min_confidence = NULL, verbose = NULL) .Call(wrap__lint_data, files, journal, mode, ignore_rules, min_confidence, verbose)

#' Auto-fix backing `jssfix()` — internal. Lints `files` (named
#' character vector, same shape as `render`), then hands the report to
#' `fixer::apply_fixes`, which reads/writes the files at the paths
#' given by `names(files)` on disk (atomic write + re-validation with
#' rollback on regression). In dry-run mode nothing is written and the
#' captured `output` holds the unified diffs that would be applied.
#' @noRd
fix_data <- function(files, dry_run = FALSE, rules = NULL, journal = NULL, mode = NULL, ignore_rules = NULL, min_confidence = NULL, verbose = NULL) .Call(wrap__fix_data, files, dry_run, rules, journal, mode, ignore_rules, min_confidence, verbose)

# nolint end
