# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib jsslintr, .registration = TRUE
NULL

#' Lints `files` and renders the report in `output` format. Mirrors
#' `jsslint::render` (the PyO3 binding) / the WASM binding's `render()`.
#' @param files A named character vector: names are file paths
#'   (`.tex`/`.ltx`/`.bib`), values are the file contents.
#' @param journal Journal identifier (default: `"jss"`).
#' @param mode `"author"` or `"reviewer"` (default: `"author"`).
#' @param output `"terminal"`, `"json"`, `"sarif"`, or `"html"`
#'   (default: `"terminal"`).
#' @param ignore_rules Comma-separated rule ids to suppress.
#' @param min_confidence `"low"`, `"medium"`, or `"high"`.
#' @param fail_on `"error"`, `"warning"`, or `"info"`.
#' @param source_root Base directory for SARIF artifact URIs.
#' @param verbose Enable diagnostic output on stderr.
#' @return The rendered report, as a single string.
#' @export
render <- function(files, journal = NULL, mode = NULL, output = NULL, ignore_rules = NULL, min_confidence = NULL, fail_on = NULL, source_root = NULL, verbose = NULL) .Call(wrap__render, files, journal, mode, output, ignore_rules, min_confidence, fail_on, source_root, verbose)

# nolint end
