//! `jss-lint init` — mirrors `texlint/init.py` (spec 010, plus the
//! precision-DB-aware suppression follow-up). CLI-only (not
//! `jsslint-core`): the SQLite dependency this needs
//! (`eval/precision-history.db`, an internal maintainer/eval-harness
//! artifact tracked in *this* repo, never present in a downstream
//! author's manuscript directory) has no business being pulled into
//! the WASM/R/Python bindings, which only ever lint someone else's
//! manuscript and have no use for this repo's own precision history.

use jsslint_core::report::{ComplianceReport, Violation};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

const DEFAULT_DB_PATH: &str = "eval/precision-history.db";

pub struct InitResult {
    pub config_path: PathBuf,
    /// Mirrors `init.py::InitResult.wrote`; unused by `main.rs`'s
    /// caller (same as Python's `init_cmd`, which doesn't read it
    /// either) but kept for API parity.
    #[allow(dead_code)]
    pub wrote: bool,
    pub contents: String,
    pub must_fix_count: usize,
    pub suppressed_count: usize,
    pub total_violations: usize,
}

pub enum InitError {
    /// `.jss-lint.toml` exists and `--force` was not set. Mirrors
    /// `init.py::InitRefusedError`.
    Refused(String),
    /// Mirrors `init.py::run`'s `ValueError` for an out-of-range
    /// `--threshold`.
    InvalidThreshold(String),
}

/// Reads the latest per-rule precision values from the eval-jss DB.
/// Returns `({}, None)` when the DB is missing/unreadable/empty —
/// mirrors `init.py::_read_precision_db`.
fn read_precision_db(db_path: &Path) -> (HashMap<String, f64>, Option<String>) {
    if !db_path.is_file() {
        return (HashMap::new(), None);
    }
    let Ok(conn) =
        rusqlite::Connection::open_with_flags(db_path, rusqlite::OpenFlags::SQLITE_OPEN_READ_ONLY)
    else {
        return (HashMap::new(), None);
    };
    let latest: Option<(i64, String)> = conn
        .query_row(
            "SELECT id, label FROM iterations ORDER BY id DESC LIMIT 1",
            [],
            |row| Ok((row.get(0)?, row.get(1)?)),
        )
        .ok();
    let Some((latest_id, label)) = latest else {
        return (HashMap::new(), None);
    };

    let mut stmt = match conn.prepare(
        "SELECT rule_id, precision FROM iteration_rule_stats \
         WHERE iteration_id = ?1 AND scope = 'full' AND precision IS NOT NULL",
    ) {
        Ok(s) => s,
        Err(_) => return (HashMap::new(), None),
    };
    let rows = stmt.query_map([latest_id], |row| {
        let rule_id: String = row.get(0)?;
        let precision: f64 = row.get(1)?;
        Ok((rule_id, precision))
    });
    let Ok(rows) = rows else {
        return (HashMap::new(), None);
    };
    let map: HashMap<String, f64> = rows.filter_map(Result::ok).collect();
    (map, Some(label))
}

/// Hand-rolled TOML (no `toml` writer dep needed for this one small
/// shape). Mirrors `init.py::_render_toml`.
fn render_toml(journal: &str, ignored_rules: &[(String, String)], threshold: f64) -> String {
    let today = crate::localdate::today_iso();
    let mut lines = vec![
        format!("journal = \"{journal}\""),
        String::new(),
        format!("# auto-generated by `jss-lint init` on {today}"),
        format!("# threshold = {threshold:.2} (matches Constitution §VI)"),
        String::new(),
        "ignore_rules = [".to_string(),
    ];
    let mut sorted = ignored_rules.to_vec();
    sorted.sort_by(|a, b| a.0.cmp(&b.0));
    for (rule_id, comment) in &sorted {
        lines.push(format!("  # {rule_id}: {comment}"));
        lines.push(format!("  \"{rule_id}\","));
    }
    lines.push("]".to_string());
    lines.push(String::new());
    lines.join("\n")
}

fn atomic_write(target: &Path, contents: &str) -> std::io::Result<()> {
    let parent = target.parent().unwrap_or_else(|| Path::new("."));
    let file_name = target
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();
    let tmp_path = parent.join(format!(
        ".jss-lint.{}.{}.tmp",
        std::process::id(),
        file_name
    ));
    std::fs::write(&tmp_path, contents.as_bytes())?;
    std::fs::rename(&tmp_path, target)?;
    Ok(())
}

/// Builds (and optionally writes) a `.jss-lint.toml` for a manuscript.
/// Mirrors `init.py::run`.
#[allow(clippy::too_many_arguments)]
pub fn run(
    target_dir: &Path,
    report: &ComplianceReport,
    force: bool,
    dry_run: bool,
    threshold: f64,
    journal: &str,
    precision_db_path: Option<&Path>,
) -> Result<InitResult, InitError> {
    if !(0.0..=1.0).contains(&threshold) {
        return Err(InitError::InvalidThreshold(format!(
            "--threshold must be between 0 and 1; got {threshold}"
        )));
    }

    let config_path = crate::pathlib_normalize(&target_dir.join(".jss-lint.toml"));
    if !dry_run && config_path.exists() && !force {
        return Err(InitError::Refused(format!(
            "refusing to overwrite {}; pass --force to overwrite",
            config_path.display()
        )));
    }

    let mut by_rule: HashMap<&str, Vec<&Violation>> = HashMap::new();
    for v in &report.violations {
        by_rule.entry(v.rule_id.as_str()).or_default().push(v);
    }

    let candidates: Vec<PathBuf> = match precision_db_path {
        Some(p) => vec![p.to_path_buf()],
        None => vec![
            target_dir.join("eval").join("precision-history.db"),
            PathBuf::from(DEFAULT_DB_PATH),
        ],
    };
    let mut precision_per_rule: HashMap<String, f64> = HashMap::new();
    let mut db_label: Option<String> = None;
    for candidate in &candidates {
        if candidate.is_file() {
            let (map, label) = read_precision_db(candidate);
            if !map.is_empty() {
                precision_per_rule = map;
                db_label = label;
                break;
            }
        }
    }

    let mut ignored: Vec<(String, String)> = Vec::new();
    if !precision_per_rule.is_empty() {
        let label = db_label.as_deref().unwrap_or("None");
        for (rid, precision) in &precision_per_rule {
            if *precision < threshold {
                let comment =
                    format!("precision {precision:.2} (run {label}), below {threshold:.2}");
                ignored.push((rid.clone(), comment));
            }
        }
    }

    let contents = render_toml(journal, &ignored, threshold);

    let wrote = if !dry_run {
        atomic_write(&config_path, &contents)
            .unwrap_or_else(|e| panic!("failed to write {}: {e}", config_path.display()));
        true
    } else {
        false
    };

    Ok(InitResult {
        config_path,
        wrote,
        contents,
        must_fix_count: by_rule.len(),
        suppressed_count: ignored.len(),
        total_violations: report.violations.len(),
    })
}
