# AUTO-GENERATED from specs/003-jss-rule-catalogue/catalogue.yaml.
# Do not edit by hand; run `python -m tools.generate_catalogue_data`.

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from texlint.api import Severity

# One entry per active rule in catalogue.yaml.
RULES: Mapping[str, Mapping[str, object]] = MappingProxyType({
    'JSS-PRE-001': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'Document class must be jss with a valid class option (article, codesnippet, bookreview, softwarereview)',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:37',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'Document class must be jss with a valid class option (article, codesnippet, bookreview, softwarereview).',
    }),
    'JSS-PRE-002': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'Preamble defines \\Address{} with author affiliation and contact',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Address',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'Preamble defines \\Address{} with author affiliation and contact.',
    }),
    'JSS-PRE-003': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'When \\title{} contains LaTeX markup, preamble also defines \\Plaintitle{} with the markup-free form',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plaintitle',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'When \\title{} contains LaTeX markup, preamble also defines \\Plaintitle{} with the markup-free form.',
    }),
    'JSS-PRE-004': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": '\\Abstract{} is present and overrides the sentinel placeholder from jss.cls',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:120',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": '\\Abstract{} is present and overrides the sentinel placeholder from jss.cls.',
    }),
    'JSS-PRE-005': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": '\\Keywords{} is present and overrides the sentinel placeholder from jss.cls',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:197',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": '\\Keywords{} is present and overrides the sentinel placeholder from jss.cls.',
    }),
    'JSS-PRE-006': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.WARNING,
        "message_template": '\\Plaintitle, \\Plainauthor, \\Plainkeywords contain no LaTeX markup (PDF metadata must be plain text)',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plaintitle',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": '\\Plaintitle, \\Plainauthor, \\Plainkeywords contain no LaTeX markup (PDF metadata must be plain text).',
    }),
    'JSS-PRE-007': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'When \\author{} contains LaTeX markup, preamble also defines \\Plainauthor{} with the markup-free form',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plainauthor',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'When \\author{} contains LaTeX markup, preamble also defines \\Plainauthor{} with the markup-free form.',
    }),
    'JSS-PRE-008': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'When \\Keywords{} contains LaTeX markup, preamble also defines \\Plainkeywords{} with the markup-free form',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plainkeywords',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'When \\Keywords{} contains LaTeX markup, preamble also defines \\Plainkeywords{} with the markup-free form.',
    }),
    'JSS-STRUCT-001': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Document ends with a summary / discussion section before the bibliography',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:378',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Document ends with a summary / discussion section before the bibliography.',
    }),
    'JSS-STRUCT-002': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Acknowledgments section uses American spelling (not "Acknowledgements")',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:407',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Acknowledgments section uses American spelling (not "Acknowledgements").',
    }),
    'JSS-STRUCT-003': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Appendix sections have proper titles instead of a bare "Appendix"',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:438',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Appendix sections have proper titles instead of a bare "Appendix".',
    }),
    'JSS-STRUCT-004': MappingProxyType({
        "category": 'structure',
        "severity": Severity.ERROR,
        "message_template": 'References are declared via \\bibliography{} rather than a hand-written thebibliography environment',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'References are declared via \\bibliography{} rather than a hand-written thebibliography environment.',
    }),
    'JSS-STRUCT-005': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": '\\author{} separates authors with \\And or \\AND (not lowercase \\and)',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:22',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": '\\author{} separates authors with \\And or \\AND (not lowercase \\and).',
    }),
    'JSS-STRUCT-006': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Appendix follows the bibliography with a \\newpage (or \\clearpage) separator',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:430',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Appendix follows the bibliography with a \\newpage (or \\clearpage) separator.',
    }),
    'JSS-MARKUP-001': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Programming-language names in prose are wrapped in \\proglang{}',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\proglang',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "confidence": 'medium',
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Programming-language names in prose are wrapped in \\proglang{}.',
    }),
    'JSS-MARKUP-002': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Software-package names in prose are wrapped in \\pkg{}',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\pkg',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Software-package names in prose are wrapped in \\pkg{}.',
    }),
    'JSS-MARKUP-003': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Inline function, argument, command names, and R sentinel values are wrapped in \\code{}',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\code',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Inline function, argument, and command names — and bare R sentinel values such as NULL, NA, TRUE, FALSE — are wrapped in \\code{}.',
    }),
    'JSS-MARKUP-004': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Section titles containing markup supply a plain-text shim via \\section[plain]{markup}',
        "authority": 'style_guide',
        "authority_ref": '#my-latex-paper-does-not-compile-when-there-is-jss-markup-in-section-titles-what-should-i-do',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Section titles containing markup supply a plain-text shim via \\section[plain]{markup}.',
    }),
    'JSS-CITE-002': MappingProxyType({
        "category": 'citations',
        "severity": Severity.WARNING,
        "message_template": 'First occurrence of a software package has a citation within the same paragraph',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "confidence": 'medium',
        "guide_section": '§3.2 Citations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#citations',
        "explanation": 'First occurrence of a software package has a citation within the same paragraph. See §3.2 Citations.',
    }),
    'JSS-CITE-003': MappingProxyType({
        "category": 'citations',
        "severity": Severity.WARNING,
        "message_template": 'Avoid bracket-in-bracket citation forms like (\\cite{...}); use \\citep{...} instead',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-different-cite-citet-citep-commands-about',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§3.2 Citations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#citations',
        "explanation": 'Avoid bracket-in-bracket citation forms like (\\cite{...}); use \\citep{...} instead.',
    }),
    'JSS-CITE-004': MappingProxyType({
        "category": 'citations',
        "severity": Severity.WARNING,
        "message_template": 'Citations use natbib commands (\\cite, \\citet, \\citep, \\citealp) rather than hardcoded author-year text',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:62',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§3.2 Citations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#citations',
        "explanation": 'Citations use natbib commands (\\cite, \\citet, \\citep, \\citealp) rather than hardcoded author-year text.',
    }),
    'JSS-REFS-001': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'BibTeX entries carry a year field so natbib author-year citations render correctly',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX entries carry a year field so natbib author-year citations render correctly.',
    }),
    'JSS-REFS-003': MappingProxyType({
        "category": 'references',
        "severity": Severity.INFO,
        "message_template": 'BibTeX entries include a doi field where one is available (advisory)',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:421',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX entries include a doi field where one is available (advisory).',
    }),
    'JSS-REFS-004': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'BibTeX titles use JSS markup (\\proglang, \\pkg, \\code) for language and package names',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX titles use JSS markup (\\proglang, \\pkg, \\code) for language and package names.',
    }),
    'JSS-REFS-005': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'Journal titles in BibTeX entries are not abbreviated',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:473',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'Journal titles in BibTeX entries are not abbreviated.',
    }),
    'JSS-REFS-006': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'BibTeX titles are in title style — loose heuristic (flags lowercase first word or unusual mixed case)',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX titles are in title style — loose heuristic (flags lowercase first word or unusual mixed case).',
    }),
    'JSS-REFS-007': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'Journal titles in BibTeX entries are in title case',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:473',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'Journal titles in BibTeX entries are in title case.',
    }),
    'JSS-BIBTEX-001': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'Every BibTeX entry has a non-empty citation key',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'Every BibTeX entry has a non-empty citation key.',
    }),
    'JSS-BIBTEX-002': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'BibTeX citation keys are unique within the database',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'BibTeX citation keys are unique within the database.',
    }),
    'JSS-BIBTEX-003': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'BibTeX entries carry the fields required for their entry type (article, book, inproceedings, …)',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'BibTeX entries carry the fields required for their entry type (article, book, inproceedings, …).',
    }),
    'JSS-BIBTEX-004': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.WARNING,
        "message_template": 'Entries with 6+ authors use \\shortcites{} or the shortnames class option is enabled',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:45',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'Entries with 6+ authors use \\shortcites{} or the shortnames class option is enabled.',
    }),
    'JSS-BIBTEX-005': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'No BibTeX field key is repeated within a single entry',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'No BibTeX field key is repeated within a single entry.',
    }),
    'JSS-NAME-001': MappingProxyType({
        "category": 'naming',
        "severity": Severity.WARNING,
        "message_template": 'Programming-language names use their canonical capitalisation',
        "authority": 'style_guide',
        "authority_ref": '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§6.1 Naming',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#naming',
        "explanation": 'Programming-language names use their canonical capitalisation.',
    }),
    'JSS-NAME-002': MappingProxyType({
        "category": 'naming',
        "severity": Severity.WARNING,
        "message_template": 'Publisher and journal names follow JSS conventions (e.g., "Springer-Verlag", "The Annals of Statistics")',
        "authority": 'style_guide',
        "authority_ref": '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        "inspects": ('bib_files',),
        "auto_fixable": True,
        "guide_section": '§6.1 Naming',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#naming',
        "explanation": 'Publisher and journal names follow JSS conventions (e.g., "Springer-Verlag", "The Annals of Statistics").',
    }),
    'JSS-CAP-001': MappingProxyType({
        "category": 'capitalization',
        "severity": Severity.WARNING,
        "message_template": '\\title{} is in title style (principal words capitalised)',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§6.2 Capitalisation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#capitalisation',
        "explanation": '\\title{} is in title style (principal words capitalised; first word after a colon capitalised).',
    }),
    'JSS-CAP-002': MappingProxyType({
        "category": 'capitalization',
        "severity": Severity.WARNING,
        "message_template": 'Section titles are in sentence style (first word capitalised; others lowercase except proper names)',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "confidence": 'medium',
        "guide_section": '§6.2 Capitalisation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#capitalisation',
        "explanation": 'Section titles are in sentence style (first word capitalised; first word after a colon capitalised; others lowercase except proper names).',
    }),
    'JSS-CAP-004': MappingProxyType({
        "category": 'capitalization',
        "severity": Severity.WARNING,
        "message_template": '\\Keywords{} is comma-separated and in sentence case',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:48',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§6.2 Capitalisation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#capitalisation',
        "explanation": '\\Keywords{} is comma-separated and in sentence case.',
    }),
    'JSS-TYPO-001': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": 'Figure and table captions end with a period',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": 'Figure and table captions end with a period.',
    }),
    'JSS-TYPO-002': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": 'Figure / table captions avoid emphasis macros wrapping the whole caption (\\emph, \\textbf, \\textit on full caption)',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": 'Figure / table captions avoid emphasis macros wrapping the whole caption (\\emph, \\textbf, \\textit on full caption).',
    }),
    'JSS-TYPO-003': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": 'Tables do not use footnote-style annotations; annotations go in the caption',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": 'Tables do not use footnote-style annotations; annotations go in the caption.',
    }),
    'JSS-TYPO-004': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": '\\caption{} appears after the figure / table content, not before',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": '\\caption{} appears after the figure / table content, not before.',
    }),
    'JSS-ABBR-001': MappingProxyType({
        "category": 'abbreviations',
        "severity": Severity.WARNING,
        "message_template": 'Abbreviations are in uppercase without periods or additional formatting',
        "authority": 'style_guide',
        "authority_ref": '#how-should-abbrevations-be-formatted',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§6.3 Abbreviations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#abbreviations',
        "explanation": 'Abbreviations are in uppercase without periods or additional formatting.',
    }),
    'JSS-CODE-001': MappingProxyType({
        "category": 'code_style',
        "severity": Severity.WARNING,
        "message_template": 'Verbatim / CodeInput blocks do not contain comments; comments belong in the surrounding LaTeX text',
        "authority": 'style_guide',
        "authority_ref": '#how-should-code-be-formatted-in-the-manuscript',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.2 Code style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#code-style',
        "explanation": 'Verbatim / CodeInput blocks do not contain comments; comments belong in the surrounding LaTeX text.',
    }),
    'JSS-CODE-002': MappingProxyType({
        "category": 'code_style',
        "severity": Severity.WARNING,
        "message_template": 'R library() and data() calls quote their first argument',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.2 Code style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#code-style',
        "explanation": 'R library() and data() calls quote their first argument.',
    }),
    'JSS-CODE-003': MappingProxyType({
        "category": 'code_style',
        "severity": Severity.WARNING,
        "message_template": 'Code samples use spaces around operators and after commas',
        "authority": 'style_guide',
        "authority_ref": '#how-should-code-be-formatted-in-the-manuscript',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.2 Code style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#code-style',
        "explanation": 'Code samples use spaces around operators and after commas.',
    }),
    'JSS-WIDTH-001': MappingProxyType({
        "category": 'code_width',
        "severity": Severity.WARNING,
        "message_template": 'Code input / output inside Sinput / CodeInput / CodeOutput environments fits within the configured column limit',
        "authority": 'style_guide',
        "authority_ref": '#how-should-code-be-formatted-in-the-manuscript',
        "inspects": ('raw_source',),
        "auto_fixable": False,
        "guide_section": '§7.1 Line width',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#line-width',
        "explanation": 'Code input / output inside Sinput / CodeInput / CodeOutput environments fits within the configured column limit.',
    }),
    'JSS-OPER-001': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Symbol-plus-noun constructs like p-value and t-statistic are typeset as $p$~value and $t$~statistic (tie, no hyphen)',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Symbol-plus-noun constructs like p-value and t-statistic are typeset as $p$~value and $t$~statistic (tie, no hyphen).',
    }),
    'JSS-OPER-002': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Transpose is typeset with \\top rather than a superscript prime or literal T',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Transpose is typeset with \\top rather than a superscript prime or literal T.',
    }),
    'JSS-OPER-003': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Display equations have no blank lines immediately before or after (use % to suppress paragraph breaks)',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:154',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Display equations have no blank lines immediately before or after (use % to suppress paragraph breaks).',
    }),
    'JSS-OPER-004': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Expectation / variance / covariance / probability use jss.cls shortcuts \\E, \\VAR, \\COV, \\Prob',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:484',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Expectation / variance / covariance / probability use jss.cls shortcuts \\E, \\VAR, \\COV, \\Prob.',
    }),
    'JSS-XREF-001': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Figures and tables are referenced via \\ref{} rather than by manual numbering',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Figures and tables are referenced via \\ref{} rather than by manual numbering (e.g. "Figure 2").',
    }),
    'JSS-XREF-002': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.INFO,
        "message_template": 'Equation references prefer Equation~\\ref{...} (capitalised) over bare (\\ref{...}) or \\eqref{...}',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Equation references prefer Equation~\\ref{...} (capitalised) over bare (\\ref{...}) or \\eqref{...}; both \\eqref and (\\ref) render as the parenthesised form reviewers discourage.',
    }),
    'JSS-XREF-003': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Cross-references to subsections use "Section x.y" rather than "Subsection x.y"',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Cross-references to subsections use "Section x.y" rather than "Subsection x.y".',
    }),
    'JSS-XREF-004': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.INFO,
        "message_template": 'Numbered equations carry \\label{} and are referenced from the text',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Numbered equations carry \\label{} and are referenced from the text.',
    }),
    'JSS-XREF-005': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Figures and tables carry \\label{} and are referenced from the text',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Figures and tables carry \\label{} and are referenced from the text.',
    }),
    'JSS-XREF-006': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Figure and table floats carry a \\caption{}',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Figure and table floats carry a \\caption{} so they are numbered and can be referenced from the text.',
    }),
    'JSS-XREF-007': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.INFO,
        "message_template": 'Cross-reference nouns are spelled out (Figure/Section/Table), not abbreviated (Fig./Sec./Tab.)',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": "Cross-reference nouns are spelled out (Figure/Section/Table), not abbreviated (Fig./Sec./Tab.); the figure/section/table analogue of JSS-XREF-002's Eq. -> Equation rule.",
    }),
    'JSS-HOUSE-001': MappingProxyType({
        "category": 'house_style',
        "severity": Severity.WARNING,
        "message_template": '"e.g." and "i.e." are followed by a comma so LaTeX does not treat the period as a sentence end',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§8.1 House style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#house-style',
        "explanation": '"e.g." and "i.e." are followed by a comma so LaTeX does not treat the period as a sentence end.',
    }),
    'JSS-HOUSE-002': MappingProxyType({
        "category": 'house_style',
        "severity": Severity.WARNING,
        "message_template": 'Book editions are indicated as 2nd, 3rd, etc., not as "second" or "2e"',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('bib_files',),
        "auto_fixable": True,
        "guide_section": '§8.1 House style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#house-style',
        "explanation": 'Book editions are indicated as 2nd, 3rd, etc., not as "second" or "2e".',
    }),
    'JSS-HOUSE-003': MappingProxyType({
        "category": 'house_style',
        "severity": Severity.INFO,
        "message_template": 'Preamble avoids loading LaTeX packages that jss.cls already provides (graphicx, xcolor, ae, fancyvrb, hyperref)',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:54',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§8.1 House style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#house-style',
        "explanation": 'Preamble avoids loading LaTeX packages that jss.cls already provides (graphicx, xcolor, ae, fancyvrb, hyperref).',
    }),
    'JSS-PROJECT-001': MappingProxyType({
        "category": 'project',
        "severity": Severity.ERROR,
        "message_template": 'A cycle exists in the \\input/\\include/\\subfile/\\bibliography reference graph',
        "authority": 'author_instructions',
        "authority_ref": 'multi-file-projects',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": 'internal',
        "explanation": 'The resolver found a cycle while following \\input/\\include/\\subfile/\\bibliography references from the root file. The file that closes the cycle is reported once and is not processed a second time.',
    }),
    'JSS-PROJECT-002': MappingProxyType({
        "category": 'project',
        "severity": Severity.ERROR,
        "message_template": 'A \\input/\\include/\\subfile/\\bibliography target could not be found',
        "authority": 'author_instructions',
        "authority_ref": 'multi-file-projects',
        "inspects": ('tex_files', 'bib_files'),
        "auto_fixable": False,
        "guide_section": 'internal',
        "explanation": "The resolver followed a \\input/\\include/\\subfile/\\bibliography reference to a name that does not exist under the referencing file's directory, TEXINPUTS, or BIBINPUTS search path.",
    }),
})

RETIRED_RULE_IDS: frozenset[str] = frozenset({
    'JSS-ABBR-002',
    'JSS-CAP-003',
    'JSS-CITE-001',
    'JSS-REFS-002',
})

# Mechanically-decidable rules: the linter is authoritative, so the
# eval pipeline auto-accepts their firings (see catalogue.yaml).
DETERMINISTIC_RULE_IDS: frozenset[str] = frozenset({
    'JSS-BIBTEX-001',
    'JSS-BIBTEX-002',
    'JSS-BIBTEX-003',
    'JSS-BIBTEX-004',
    'JSS-BIBTEX-005',
    'JSS-CITE-003',
    'JSS-CODE-001',
    'JSS-CODE-002',
    'JSS-HOUSE-002',
    'JSS-HOUSE-003',
    'JSS-OPER-003',
    'JSS-PRE-001',
    'JSS-PRE-002',
    'JSS-PRE-003',
    'JSS-PRE-004',
    'JSS-PRE-005',
    'JSS-PRE-006',
    'JSS-PRE-007',
    'JSS-PRE-008',
    'JSS-PROJECT-001',
    'JSS-PROJECT-002',
    'JSS-REFS-001',
    'JSS-REFS-007',
    'JSS-STRUCT-002',
    'JSS-STRUCT-003',
    'JSS-STRUCT-004',
    'JSS-STRUCT-006',
    'JSS-TYPO-001',
    'JSS-TYPO-002',
    'JSS-TYPO-003',
    'JSS-TYPO-004',
    'JSS-WIDTH-001',
    'JSS-XREF-002',
    'JSS-XREF-004',
})

# Rule-set provenance (spec 027 item D). GUIDE_SOURCE is the
# report/JSON rendering; GUIDE_EDITION and SOURCE_VENDORED_AT are its
# parts, which `--version` line 3 lays out differently.
RULESET_VERSION: str = '2026-09-07'
RULESET_FINGERPRINT: str = 'sha256:e9715b94cfb8d199fcce76c4fb17862a35ebcae4ada77c41cd3db08267aceab5'
GUIDE_EDITION: str = 'jss.cls 3.3'
SOURCE_VENDORED_AT: str = '2021-05-23'
GUIDE_SOURCE: str = 'jss.cls 3.3 (2021-05-23)'

# Measured recall, from specs/003-jss-rule-catalogue/recall.json
# (spec 027 item A). RECALL_RUN pins the run; RECALL holds the
# per-rule counts. Rules absent from RECALL are unmeasured.
RECALL_RUN: Mapping[str, object] = MappingProxyType({
    'run_timestamp': '2026-07-19T10:30:02Z',
    'corpus_hash': '70951d5371df0734',
    'min_plants': 10,
    'papers': 17,
    'tp': 1587,
    'fn': 380,
})

RECALL: Mapping[str, tuple[int, int]] = MappingProxyType({
    'JSS-ABBR-001': (4, 0),
    'JSS-BIBTEX-002': (2, 0),
    'JSS-BIBTEX-003': (5, 0),
    'JSS-BIBTEX-004': (13, 3),
    'JSS-BIBTEX-005': (2, 0),
    'JSS-CAP-001': (6, 0),
    'JSS-CAP-002': (70, 20),
    'JSS-CAP-004': (2, 0),
    'JSS-CITE-002': (8, 4),
    'JSS-CITE-003': (44, 0),
    'JSS-CITE-004': (1, 0),
    'JSS-CODE-001': (56, 1),
    'JSS-CODE-002': (70, 2),
    'JSS-CODE-003': (203, 25),
    'JSS-HOUSE-001': (32, 28),
    'JSS-HOUSE-002': (5, 0),
    'JSS-HOUSE-003': (10, 0),
    'JSS-MARKUP-001': (38, 6),
    'JSS-MARKUP-002': (3, 4),
    'JSS-MARKUP-003': (168, 114),
    'JSS-MARKUP-004': (1, 0),
    'JSS-NAME-001': (1, 0),
    'JSS-NAME-002': (21, 2),
    'JSS-OPER-001': (5, 4),
    'JSS-OPER-002': (14, 5),
    'JSS-OPER-003': (55, 16),
    'JSS-OPER-004': (47, 31),
    'JSS-PRE-003': (1, 0),
    'JSS-PRE-004': (1, 0),
    'JSS-PRE-005': (1, 0),
    'JSS-PRE-006': (4, 0),
    'JSS-PRE-007': (1, 0),
    'JSS-REFS-003': (189, 90),
    'JSS-REFS-004': (66, 8),
    'JSS-REFS-005': (2, 1),
    'JSS-REFS-006': (105, 3),
    'JSS-REFS-007': (26, 0),
    'JSS-STRUCT-001': (4, 0),
    'JSS-STRUCT-002': (4, 0),
    'JSS-STRUCT-003': (1, 0),
    'JSS-STRUCT-004': (1, 0),
    'JSS-STRUCT-005': (1, 1),
    'JSS-STRUCT-006': (1, 1),
    'JSS-TYPO-001': (32, 5),
    'JSS-TYPO-003': (1, 0),
    'JSS-TYPO-004': (20, 0),
    'JSS-WIDTH-001': (13, 6),
    'JSS-XREF-001': (1, 0),
    'JSS-XREF-002': (42, 0),
    'JSS-XREF-004': (139, 0),
    'JSS-XREF-005': (19, 0),
    'JSS-XREF-006': (1, 0),
    'JSS-XREF-007': (25, 0),
})

# Guide coverage, from specs/003-jss-rule-catalogue/guide-coverage.yaml
# (spec 027 item A): which provisions of the four authorities the rule
# set checks, and which it does not.
COVERAGE: tuple[Mapping[str, object], ...] = (
    MappingProxyType({
        'id': 'CLS-001',
        'source': 'jss_cls',
        'section': 'jss.cls:37',
        'provision': 'Manuscript declares exactly one of `article`, `codesnippet`, `bookreview`, `softwarereview` as the class option',
        'status': 'checked',
        "rules": ('JSS-PRE-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-002',
        'source': 'jss_cls',
        'section': 'jss.cls:45',
        'provision': '`shortnames` class option available for natbib short-form names',
        'status': 'checked',
        "rules": ('JSS-BIBTEX-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-003',
        'source': 'jss_cls',
        'section': 'jss.cls:46',
        'provision': '`nojss` class option turns off JSS header/footer (used for vignettes)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'the class *offers* the option; nothing obliges an author to use it. Not a vignette-scope gap — JSS-PRE-001 accepts `[nojss]` and preamble.py gates the vignette waiver on it',
    }),
    MappingProxyType({
        'id': 'CLS-004',
        'source': 'jss_cls',
        'section': 'jss.cls:47',
        'provision': '`notitle`, `noheadings`, `nofooter` class options exist',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'vignette-only',
    }),
    MappingProxyType({
        'id': 'CLS-005',
        'source': 'jss_cls',
        'section': 'jss.cls:59',
        'provision': '`natbib` loaded with `[authoryear,round]` (or `[authoryear,round,longnamesfirst]` when `shortnames` is off); `\\bibpunct` set to `(){};a,`',
        'status': 'checked',
        "rules": ('JSS-CITE-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-006',
        'source': 'jss_cls',
        'section': 'jss.cls:65',
        'provision': 'Bibliography style is `jss` (i.e., `\\bibliographystyle{jss}`)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'set implicitly by jss.cls; no author action required',
    }),
    MappingProxyType({
        'id': 'CLS-007',
        'source': 'jss_cls',
        'section': 'jss.cls:81',
        'provision': '`\\Address{}` metadata command (required in preamble)',
        'status': 'checked',
        "rules": ('JSS-PRE-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-008',
        'source': 'jss_cls',
        'section': 'jss.cls:82',
        'provision': '`\\Plaintitle{}` metadata command (plain-text title without LaTeX markup)',
        'status': 'checked',
        "rules": ('JSS-PRE-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-009',
        'source': 'jss_cls',
        'section': 'jss.cls:83',
        'provision': '`\\Shorttitle{}` metadata command (running title with markup allowed)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'no rule enforces its presence; author-facing optional, candidate follow-up',
    }),
    MappingProxyType({
        'id': 'CLS-010',
        'source': 'jss_cls',
        'section': 'jss.cls:84',
        'provision': '`\\Plainauthor{}` metadata command (author list without affiliations)',
        'status': 'checked',
        "rules": ('JSS-PRE-007',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-011',
        'source': 'jss_cls',
        'section': 'jss.cls:85',
        'provision': '`\\Volume{}` metadata command',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'editorial metadata, set by JSS not by author',
    }),
    MappingProxyType({
        'id': 'CLS-012',
        'source': 'jss_cls',
        'section': 'jss.cls:86',
        'provision': '`\\Year{}` metadata command',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'editorial metadata',
    }),
    MappingProxyType({
        'id': 'CLS-013',
        'source': 'jss_cls',
        'section': 'jss.cls:87',
        'provision': '`\\Month{}` metadata command',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'editorial metadata',
    }),
    MappingProxyType({
        'id': 'CLS-014',
        'source': 'jss_cls',
        'section': 'jss.cls:88',
        'provision': '`\\Issue{}` metadata command',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'editorial metadata',
    }),
    MappingProxyType({
        'id': 'CLS-015',
        'source': 'jss_cls',
        'section': 'jss.cls:89',
        'provision': '`\\Submitdate{}` metadata command',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'editorial metadata',
    }),
    MappingProxyType({
        'id': 'CLS-016',
        'source': 'jss_cls',
        'section': 'jss.cls:91',
        'provision': '`\\Acceptdate{}` metadata command (articles / code snippets)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'editorial metadata',
    }),
    MappingProxyType({
        'id': 'CLS-017',
        'source': 'jss_cls',
        'section': 'jss.cls:92',
        'provision': '`\\Abstract{}` is required and non-placeholder (default in 120 is a sentinel error)',
        'status': 'checked',
        "rules": ('JSS-PRE-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-018',
        'source': 'jss_cls',
        'section': 'jss.cls:93',
        'provision': '`\\Keywords{}` is required and non-placeholder (default in 197 is a sentinel error)',
        'status': 'checked',
        "rules": ('JSS-PRE-005',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-019',
        'source': 'jss_cls',
        'section': 'jss.cls:94',
        'provision': '`\\Plainkeywords{}` metadata command',
        'status': 'checked',
        "rules": ('JSS-PRE-008',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-020',
        'source': 'jss_cls',
        'section': 'jss.cls:96',
        'provision': '`\\Reviewer`, `\\Booktitle`, `\\Bookauthor`, `\\Publisher`, `\\Pubaddress`, `\\Pubyear`, `\\ISBN`, `\\Pages`, `\\Price`, `\\Plainreviewer`, `\\Softwaretitle`, `\\URL`, `\\DOI` metadata commands exist for `bookreview` / `softwarereview` classes',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'review class types deferred (spec scope = `article` class)',
    }),
    MappingProxyType({
        'id': 'CLS-021',
        'source': 'jss_cls',
        'section': 'jss.cls:473',
        'provision': '`\\code{}` for inline code (functions, commands, arguments, literal tokens)',
        'status': 'checked',
        "rules": ('JSS-MARKUP-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-022',
        'source': 'jss_cls',
        'section': 'jss.cls:476',
        'provision': '`\\proglang{}` for programming languages and programmable systems (defined as `\\textsf`)',
        'status': 'checked',
        "rules": ('JSS-MARKUP-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-023',
        'source': 'jss_cls',
        'section': 'jss.cls:477',
        'provision': '`\\pkg{}` for software package names (medium-bold series)',
        'status': 'checked',
        "rules": ('JSS-MARKUP-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-024',
        'source': 'jss_cls',
        'section': 'jss.cls:478',
        'provision': '`\\email{}` for email addresses (generates `mailto:` link)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'used inside `\\Address`; presence implicitly covered by JSS-PRE-002',
    }),
    MappingProxyType({
        'id': 'CLS-025',
        'source': 'jss_cls',
        'section': 'jss.cls:480',
        'provision': '`\\doi{}` for DOIs (generates `https://doi.org/...` link)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'used via `\\DOI` editorial metadata',
    }),
    MappingProxyType({
        'id': 'CLS-026',
        'source': 'jss_cls',
        'section': 'jss.cls:484',
        'provision': '`\\E` math shortcut for expectation (`\\mathsf{E}`)',
        'status': 'checked',
        "rules": ('JSS-OPER-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-027',
        'source': 'jss_cls',
        'section': 'jss.cls:485',
        'provision': '`\\VAR` math shortcut for variance',
        'status': 'checked',
        "rules": ('JSS-OPER-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-028',
        'source': 'jss_cls',
        'section': 'jss.cls:486',
        'provision': '`\\COV` math shortcut for covariance',
        'status': 'checked',
        "rules": ('JSS-OPER-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-029',
        'source': 'jss_cls',
        'section': 'jss.cls:487',
        'provision': '`\\Prob` math shortcut for probability',
        'status': 'checked',
        "rules": ('JSS-OPER-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'CLS-030',
        'source': 'jss_cls',
        'section': 'jss.cls:203',
        'provision': '`Sinput` environment defined (Sweave-style)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'a class defining an environment is not an author obligation. Sinput content is linted (CODE-*, WIDTH-001), and .Rnw chunks are rewritten into Sinput envelopes precisely to reach those rules',
    }),
    MappingProxyType({
        'id': 'CLS-031',
        'source': 'jss_cls',
        'section': 'jss.cls:204',
        'provision': '`Soutput` environment defined',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'same',
    }),
    MappingProxyType({
        'id': 'CLS-032',
        'source': 'jss_cls',
        'section': 'jss.cls:205',
        'provision': '`Scode` environment defined',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'same',
    }),
    MappingProxyType({
        'id': 'CLS-033',
        'source': 'jss_cls',
        'section': 'jss.cls:206',
        'provision': '`Schunk` environment defined',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'same',
    }),
    MappingProxyType({
        'id': 'CLS-034',
        'source': 'jss_cls',
        'section': 'jss.cls:207',
        'provision': '`Code` verbatim environment (agnostic code listing)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'environment choice is author preference',
    }),
    MappingProxyType({
        'id': 'CLS-035',
        'source': 'jss_cls',
        'section': 'jss.cls:208',
        'provision': '`CodeInput` environment (preferred for command-prompt inputs)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'same',
    }),
    MappingProxyType({
        'id': 'CLS-036',
        'source': 'jss_cls',
        'section': 'jss.cls:209',
        'provision': '`CodeOutput` environment',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'same',
    }),
    MappingProxyType({
        'id': 'CLS-037',
        'source': 'jss_cls',
        'section': 'jss.cls:210',
        'provision': '`CodeChunk` wrapper environment',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'same',
    }),
    MappingProxyType({
        'id': 'CLS-038',
        'source': 'jss_cls',
        'section': 'jss.cls:211',
        'provision': 'Default figure width set to 0.8\\textwidth by `\\setkeys{Gin}{width=0.8\\textwidth}`',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'rendering-time default; no author-side enforcement',
    }),
    MappingProxyType({
        'id': 'TEX-001',
        'source': 'article_tex',
        'section': 'article.tex:1',
        'provision': 'Document class is declared as `\\documentclass[article]{jss}` (for ordinary articles)',
        'status': 'checked',
        "rules": ('JSS-PRE-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-002',
        'source': 'article_tex',
        'section': 'article.tex:6',
        'provision': 'Recommended packages are `orcidlink`, `thumbpdf`, `lmodern`',
        'status': 'out_of_scope',
        "rules": (),
        "reason": "author-choice recommendation; enforcing would false-positive on papers that don't use ORCID",
    }),
    MappingProxyType({
        'id': 'TEX-003',
        'source': 'article_tex',
        'section': 'article.tex:12',
        'provision': 'Authors MAY define article-local convenience macros (`\\class`, `\\fct`) that delegate to `\\code{}`',
        'status': 'out_of_scope',
        "rules": (),
        "reason": '"MAY" not "MUST"; author-local convenience',
    }),
    MappingProxyType({
        'id': 'TEX-004',
        'source': 'article_tex',
        'section': 'article.tex:22',
        'provision': '`\\author{...}` uses `\\And` or `\\AND` to separate authors (not comma); inline `\\orcidlink{...}` is permitted',
        'status': 'checked',
        "rules": ('JSS-STRUCT-005',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-005',
        'source': 'article_tex',
        'section': 'article.tex:24',
        'provision': '`\\Plainauthor{...}` separates authors by comma',
        'status': 'checked',
        "rules": ('JSS-PRE-007',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-006',
        'source': 'article_tex',
        'section': 'article.tex:29',
        'provision': '`\\title{...}` (with markup), `\\Plaintitle{...}` (no markup), and `\\Shorttitle{...}` (with markup) all present',
        'status': 'checked',
        "rules": ('JSS-PRE-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-007',
        'source': 'article_tex',
        'section': 'article.tex:29',
        'provision': '`\\title{}` uses **title case** (per style guide SG-007)',
        'status': 'checked',
        "rules": ('JSS-CAP-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-008',
        'source': 'article_tex',
        'section': 'article.tex:34',
        'provision': '`\\Abstract{...}` present before `\\begin{document}`',
        'status': 'checked',
        "rules": ('JSS-PRE-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-009',
        'source': 'article_tex',
        'section': 'article.tex:49',
        'provision': '`\\Keywords{...}` is comma-separated and in sentence case (per SG and comment on line 48)',
        'status': 'checked',
        "rules": ('JSS-PRE-005', 'JSS-CAP-004'),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-010',
        'source': 'article_tex',
        'section': 'article.tex:50',
        'provision': '`\\Plainkeywords{...}` mirror of `\\Keywords` without markup',
        'status': 'checked',
        "rules": ('JSS-PRE-006', 'JSS-PRE-008'),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-011',
        'source': 'article_tex',
        'section': 'article.tex:57',
        'provision': '`\\Address{...}` contains author, affiliation, postal address, `\\email{...}`, `\\url{...}`',
        'status': 'checked',
        "rules": ('JSS-PRE-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-012',
        'source': 'article_tex',
        'section': 'article.tex:86',
        'provision': 'First numbered section is Introduction; uses `\\section[plain]{markup}` to separate bookmark/PDF title from markup title',
        'status': 'checked',
        "rules": ('JSS-MARKUP-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-013',
        'source': 'article_tex',
        'section': 'article.tex:86',
        'provision': 'Section labels follow the `sec:introname` convention (`sec:intro`, `sec:models`, `sec:illustrations`, `sec:summary`)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'label-naming convention not enforced; candidate follow-up (low severity, high FP risk)',
    }),
    MappingProxyType({
        'id': 'TEX-014',
        'source': 'article_tex',
        'section': 'article.tex:378',
        'provision': 'Summary / discussion section is present',
        'status': 'checked',
        "rules": ('JSS-STRUCT-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-015',
        'source': 'article_tex',
        'section': 'article.tex:387',
        'provision': '"Computational details" is an **unnumbered** section (`\\section*{...}`)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'pattern not enforced; "Computational details" is optional per article.tex:389',
    }),
    MappingProxyType({
        'id': 'TEX-016',
        'source': 'article_tex',
        'section': 'article.tex:404',
        'provision': '"Acknowledgments" is an unnumbered section; **AE spelling** ("Acknowledgments", not "Acknowledgements") is normative (comment on line 407)',
        'status': 'checked',
        "rules": ('JSS-STRUCT-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-017',
        'source': 'article_tex',
        'section': 'article.tex:423',
        'provision': 'References are loaded via `\\bibliography{refs}` (BibTeX)',
        'status': 'checked',
        "rules": ('JSS-STRUCT-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-018',
        'source': 'article_tex',
        'section': 'article.tex:430',
        'provision': 'Appendix follows the bibliography after a page break',
        'status': 'checked',
        "rules": ('JSS-STRUCT-006',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-019',
        'source': 'article_tex',
        'section': 'article.tex:432',
        'provision': 'Appendix sections have proper titles (not just "Appendix"); labels use `app:name` convention',
        'status': 'checked',
        "rules": ('JSS-STRUCT-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-020',
        'source': 'article_tex',
        'section': 'article.tex:88',
        'provision': '`\\proglang{}`, `\\pkg{}`, `\\code{}` markup is used throughout the manuscript body (including in section titles — with plain-text shim in the optional argument)',
        'status': 'checked',
        "rules": ('JSS-MARKUP-001', 'JSS-MARKUP-002', 'JSS-MARKUP-003', 'JSS-MARKUP-004'),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-021',
        'source': 'article_tex',
        'section': 'article.tex:170',
        'provision': '`{Code}` environment used for code synopses that are not meant to be executed',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'environment choice is author preference',
    }),
    MappingProxyType({
        'id': 'TEX-022',
        'source': 'article_tex',
        'section': 'article.tex:289',
        'provision': '`{CodeChunk}` wraps matching `{CodeInput}` / `{CodeOutput}` for executed code',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'environment-wrapping pattern, author preference',
    }),
    MappingProxyType({
        'id': 'TEX-023',
        'source': 'article_tex',
        'section': 'article.tex:291',
        'provision': 'R code inputs use `R> ` as the prompt and `+  ` as the continuation prompt',
        'status': 'not_checked',
        "rules": (),
        "reason": 'implementable and no longer deferred (.Rnw shipped 2026-07): hand-written \\begin{Sinput} lines can be checked directly. The obstacle is that wrap_rnw_chunks_as_sinput re-emits .Rnw chunks as Sinput carrying raw R source with no prompts, and leaves no marker separating them from author-written Sinput — so a naive rule would fire on every Sweave manuscript. Needs a provenance flag on the envelope',
    }),
    MappingProxyType({
        'id': 'TEX-024',
        'source': 'article_tex',
        'section': 'article.tex:154',
        'provision': '`{equation}` environments have **no blank lines** before/after (blank lines are suppressed with `%` comments)',
        'status': 'checked',
        "rules": ('JSS-OPER-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-025',
        'source': 'article_tex',
        'section': 'article.tex:421',
        'provision': 'BibTeX entries carry a doi field where one is available',
        'status': 'checked',
        "rules": ('JSS-REFS-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'TEX-026',
        'source': 'article_tex',
        'section': 'article.tex:473',
        'provision': 'Journal titles in BibTeX entries are spelled out in full and in title case',
        'status': 'checked',
        "rules": ('JSS-REFS-005', 'JSS-REFS-007'),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-001',
        'source': 'style_guide',
        'section': '#general-requirements',
        'provision': 'MUST: All submissions are formatted using LaTeX and JSS style files',
        'status': 'checked',
        "rules": ('JSS-PRE-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-002',
        'source': 'style_guide',
        'section': '#general-requirements',
        'provision': 'SHOULD: Keep LaTeX code as simple as possible; avoid unnecessary packages/commands',
        'status': 'checked',
        "rules": ('JSS-HOUSE-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-003',
        'source': 'style_guide',
        'section': '#latex-subsection',
        'provision': 'SHOULD: Use pdfLaTeX to compile manuscripts to PDF',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'compiler choice is not statically visible in the manuscript source',
    }),
    MappingProxyType({
        'id': 'SG-004',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: Manuscript must be compilable by pdfLaTeX',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'compilability is a dynamic property; delegating to `jss-lint --parse` is sufficient',
    }),
    MappingProxyType({
        'id': 'SG-005',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: Use `\\proglang`, `\\pkg`, `\\code` markup throughout the paper, including titles and references',
        'status': 'checked',
        "rules": ('JSS-MARKUP-001', 'JSS-MARKUP-002', 'JSS-MARKUP-003', 'JSS-REFS-004'),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-006',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: Provide references in a `.bib` BibTeX database; cite via `\\cite`, `\\citep`, `\\citet`, etc.',
        'status': 'checked',
        "rules": ('JSS-CITE-004', 'JSS-REFS-001', 'JSS-STRUCT-004'),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-007',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: `\\title` is in title style',
        'status': 'checked',
        "rules": ('JSS-CAP-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-008',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: All titles in the BibTeX file are in title style',
        'status': 'partial',
        "rules": ('JSS-REFS-006',),
        "reason": 'JSS-REFS-002 retired 2026-06-14; JSS-REFS-006 catches entirely lowercase multi-word titles, but a title miscapitalised only in part needs semantics a word list cannot supply',
    }),
    MappingProxyType({
        'id': 'SG-009',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: `\\section`, `\\subsection`, etc. are in sentence style',
        'status': 'checked',
        "rules": ('JSS-CAP-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-010',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: Figure/table captions (annotations) are in sentence style',
        'status': 'not_checked',
        "rules": (),
        "reason": 'JSS-CAP-003 retired 2026-07-04: measured ~32% precision and ~12% recall, and the proper-noun-vs-overcapitalised distinction needs semantics a word list cannot supply',
    }),
    MappingProxyType({
        'id': 'SG-011',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: Figures, tables, and equations are marked with `\\label` and referenced by `\\ref`',
        'status': 'checked',
        "rules": ('JSS-XREF-001', 'JSS-XREF-004', 'JSS-XREF-005', 'JSS-XREF-006'),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-012',
        'source': 'style_guide',
        'section': '#what-are-the-most-important-style-guidelines-in-jss',
        'provision': 'MUST: Software packages are cited via `\\cite{}`',
        'status': 'checked',
        "rules": ('JSS-CITE-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-013',
        'source': 'style_guide',
        'section': '#what-are-the-capitalization-rules-in-jss-what-is-title-style-and-sentence-style',
        'provision': 'MUST: In sentence style, capitalise only the first word and the first word after colon/hyphen; proper names remain uppercase',
        'status': 'partial',
        "rules": ('JSS-CAP-002', 'JSS-CAP-004'),
        "reason": 'section titles and keywords are checked; captions are not, since JSS-CAP-003 was retired 2026-07-04 (see SG-010)',
    }),
    MappingProxyType({
        'id': 'SG-014',
        'source': 'style_guide',
        'section': '#what-are-the-capitalization-rules-in-jss-what-is-title-style-and-sentence-style',
        'provision': 'MUST: In title style, capitalise all principal words; articles, coordinating conjunctions, and prepositions stay lowercase unless first/last',
        'status': 'checked',
        "rules": ('JSS-CAP-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-015',
        'source': 'style_guide',
        'section': '#how-to-cite-software',
        'provision': 'SHOULD: If software has a recommended citation, use it; otherwise cite the manual or webpage',
        'status': 'checked',
        "rules": ('JSS-CITE-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-016',
        'source': 'style_guide',
        'section': '#how-to-cite-r-packages',
        'provision': 'SHOULD: Check for official R package citation on CRAN or via `citation("pkg")`; otherwise use CRAN-style reference',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'CRAN-backed validation is explicitly deferred (spec FR-023); covered in future work via an ecosystem check',
    }),
    MappingProxyType({
        'id': 'SG-017',
        'source': 'style_guide',
        'section': '#how-to-cite-r-packages',
        'provision': 'MUST: BibTeX is valid, title is in title style, `\\proglang`/`\\pkg`/`\\code` markup used appropriately',
        'status': 'partial',
        "rules": ('JSS-BIBTEX-001', 'JSS-BIBTEX-002', 'JSS-BIBTEX-003', 'JSS-BIBTEX-005', 'JSS-REFS-001', 'JSS-REFS-004', 'JSS-REFS-006'),
        "reason": 'validity and markup are checked; title style only in its entirely-lowercase form (see SG-008)',
    }),
    MappingProxyType({
        'id': 'SG-018',
        'source': 'style_guide',
        'section': '#what-are-the-different-cite-citet-citep-commands-about',
        'provision': 'DO NOT: Use brackets-within-brackets constructs like `(\\cite{...})`',
        'status': 'checked',
        "rules": ('JSS-CITE-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-019',
        'source': 'style_guide',
        'section': '#how-should-abbrevations-be-formatted',
        'provision': 'MUST: Spell abbreviations in upper-case letters without periods, small caps, italics, or additional formatting',
        'status': 'checked',
        "rules": ('JSS-ABBR-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-020',
        'source': 'style_guide',
        'section': '#how-should-abbrevations-be-formatted',
        'provision': 'MUST: Introduce all abbreviations with expansion at first use; expansion is not capitalised unless it contains proper names or starts a sentence',
        'status': 'out_of_scope',
        "rules": (),
        "reason": '2026-04-23: JSS-ABBR-002 retired (first-use tracking is implementation-brittle; author proofreading is the path to compliance)',
    }),
    MappingProxyType({
        'id': 'SG-021',
        'source': 'style_guide',
        'section': '#how-to-format-figuretable-captions',
        'provision': 'MUST: Captions appear below the corresponding figure/table',
        'status': 'checked',
        "rules": ('JSS-TYPO-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-022',
        'source': 'style_guide',
        'section': '#how-to-format-figuretable-captions',
        'provision': 'MUST: Captions are in sentence style and end with a period',
        'status': 'partial',
        "rules": ('JSS-TYPO-001',),
        "reason": 'the trailing period is checked; caption sentence style is not, since JSS-CAP-003 was retired 2026-07-04 (see SG-010)',
    }),
    MappingProxyType({
        'id': 'SG-023',
        'source': 'style_guide',
        'section': '#how-to-format-figuretable-captions',
        'provision': 'DO NOT: Use additional formatting (`\\emph`, `\\bf`, `\\it`) inside captions',
        'status': 'checked',
        "rules": ('JSS-TYPO-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-024',
        'source': 'style_guide',
        'section': '#how-to-format-figuretable-captions',
        'provision': 'MUST: All table row/column headers are in sentence style',
        'status': 'not_checked',
        "rules": (),
        "reason": 'follow-up — requires tabular-cell-aware check; candidate follow-up',
    }),
    MappingProxyType({
        'id': 'SG-025',
        'source': 'style_guide',
        'section': '#how-to-format-figuretable-captions',
        'provision': 'DO NOT: Use footnote-style annotations in tables; annotations go in the caption',
        'status': 'checked',
        "rules": ('JSS-TYPO-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-026',
        'source': 'style_guide',
        'section': '#how-should-code-be-formatted-in-the-manuscript',
        'provision': 'SHOULD: Present code in usual text flow with sufficient spaces for readability',
        'status': 'out_of_scope',
        "rules": (),
        "reason": '"text flow" is layout / rendering, not a source-level check',
    }),
    MappingProxyType({
        'id': 'SG-027',
        'source': 'style_guide',
        'section': '#how-should-code-be-formatted-in-the-manuscript',
        'provision': 'SHOULD: Include spaces before/after operators and after commas in code (unless syntactically meaningful)',
        'status': 'checked',
        "rules": ('JSS-CODE-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-028',
        'source': 'style_guide',
        'section': '#how-should-code-be-formatted-in-the-manuscript',
        'provision': 'SHOULD: Apply consistent spacing to both inline and verbatim code',
        'status': 'checked',
        "rules": ('JSS-CODE-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-029',
        'source': 'style_guide',
        'section': '#how-should-code-be-formatted-in-the-manuscript',
        'provision': 'DO NOT: Include comments within verbatim code; place comments in normal LaTeX text',
        'status': 'checked',
        "rules": ('JSS-CODE-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-030',
        'source': 'style_guide',
        'section': '#how-should-code-be-formatted-in-the-manuscript',
        'provision': 'SHOULD: Use `\\code{...}` for inline code chunks',
        'status': 'checked',
        "rules": ('JSS-MARKUP-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-031',
        'source': 'style_guide',
        'section': '#how-should-code-be-formatted-in-the-manuscript',
        'provision': 'MUST: Code input/output fits within normal textwidth',
        'status': 'checked',
        "rules": ('JSS-WIDTH-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-032',
        'source': 'style_guide',
        'section': '#what-is-a-good-pen-to-paper-ratio-for-my-graphics',
        'provision': 'MUST: Graphics are legible on paper and on screen',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'rendering-time, not source-time',
    }),
    MappingProxyType({
        'id': 'SG-033',
        'source': 'style_guide',
        'section': '#what-is-a-good-pen-to-paper-ratio-for-my-graphics',
        'provision': 'SHOULD: Graphics annotations are about the size of the figure caption or slightly smaller',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'rendering-time',
    }),
    MappingProxyType({
        'id': 'SG-034',
        'source': 'style_guide',
        'section': '#some-of-my-graphics-files-are-very-large-what-should-i-do',
        'provision': 'SHOULD: If a vector graphic is large/slow, also supply a raster version (`.jpg`/`.png`)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'filesystem-level',
    }),
    MappingProxyType({
        'id': 'SG-035',
        'source': 'style_guide',
        'section': '#some-of-my-graphics-files-are-very-large-what-should-i-do',
        'provision': 'MUST: Annotations in raster graphics remain legible (no pixelation)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'rendering-time',
    }),
    MappingProxyType({
        'id': 'SG-036',
        'source': 'style_guide',
        'section': '#how-should-my-r-package-reflect-that-a-manuscript-about-it-was-published-in-jss',
        'provision': 'SHOULD: Include the JSS paper in `\\references{}` of relevant `.Rd` pages',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'target is R-package `.Rd` files, not the manuscript',
    }),
    MappingProxyType({
        'id': 'SG-037',
        'source': 'style_guide',
        'section': '#how-should-my-r-package-reflect-that-a-manuscript-about-it-was-published-in-jss',
        'provision': 'SHOULD: Include `CITATION` file at `inst/CITATION` within the R package',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'R-package-level, not manuscript-level',
    }),
    MappingProxyType({
        'id': 'SG-038',
        'source': 'style_guide',
        'section': '#how-should-my-r-package-reflect-that-a-manuscript-about-it-was-published-in-jss',
        'provision': 'SHOULD: Turn the JSS manuscript into a package vignette',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'advice about shipping a second artifact; the vignette is not the file under lint and its absence is unobservable from the manuscript',
    }),
    MappingProxyType({
        'id': 'SG-039',
        'source': 'style_guide',
        'section': '#how-can-i-turn-my-jss-paper-into-an-r-package-vignette',
        'provision': 'SHOULD: Use the JSS paper as the basis for the vignette',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'a provenance relation between two files, only one of which the tool is ever given',
    }),
    MappingProxyType({
        'id': 'SG-040',
        'source': 'style_guide',
        'section': '#how-can-i-turn-my-jss-paper-into-an-r-package-vignette',
        'provision': 'SHOULD: Use Sweave-style code chunks for inputs/outputs/graphics in the vignette',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'a .Rnw is chunk-based by construction, so there is no failing case to detect; a vignette that inlines results instead is a legitimate choice, not a violation',
    }),
    MappingProxyType({
        'id': 'SG-041',
        'source': 'style_guide',
        'section': '#how-can-i-turn-my-jss-paper-into-an-r-package-vignette',
        'provision': 'SHOULD: Use `\\documentclass[nojss]{jss}` to turn off JSS header/footer in the vignette',
        'status': 'not_checked',
        "rules": (),
        "reason": 'checkable now that .Rnw is parsed — the class options are already read — but only for a file known to *be* a vignette, and nothing in a .Rnw separates a vignette from a Sweave manuscript, where requiring nojss would be wrong. Needs an explicit scope signal',
    }),
    MappingProxyType({
        'id': 'SG-042',
        'source': 'style_guide',
        'section': '#how-can-i-turn-my-jss-paper-into-an-r-package-vignette',
        'provision': 'SHOULD: Cite the JSS paper in the vignette abstract or introduction',
        'status': 'out_of_scope',
        "rules": (),
        "reason": "deciding which of a vignette's references *is* the JSS paper it derives from needs knowledge the tool does not have at lint time; the corpus tooling does it by title match under human review, which is not a rule",
    }),
    MappingProxyType({
        'id': 'SG-043',
        'source': 'style_guide',
        'section': '#how-can-i-turn-my-jss-paper-into-an-r-package-vignette',
        'provision': 'SHOULD (advisory): Set `options(prompt = "R> ", continue = "+  ", width = 70, useFancyQuotes = FALSE)` invisibly at the start of the vignette',
        'status': 'not_checked',
        "rules": (),
        "reason": 'implementable, not yet written: a rule needs the pre-transform chunk text, which the parser does not keep today (hidden chunks are blanked, line counts preserved). Carrying it is the same shape as ParsedTexFile.line_offset. The open question is severity — the guide marks this advisory',
    }),
    MappingProxyType({
        'id': 'SG-044',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "Fortran" not "FORTRAN"',
        'status': 'checked',
        "rules": ('JSS-NAME-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-045',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "Java" not "JAVA" / "java"',
        'status': 'checked',
        "rules": ('JSS-NAME-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-046',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "MATLAB" not "Matlab" / "matlab"',
        'status': 'checked',
        "rules": ('JSS-NAME-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-047',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "S-PLUS" not "Splus" / "S-Plus"',
        'status': 'checked',
        "rules": ('JSS-NAME-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-048',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "The American Statistician" (with the article)',
        'status': 'checked',
        "rules": ('JSS-NAME-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-049',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "The Annals of Statistics" (with the article)',
        'status': 'checked',
        "rules": ('JSS-NAME-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-050',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "Journal of the Royal Statistical Society B" (not "..., Series B")',
        'status': 'checked',
        "rules": ('JSS-NAME-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-051',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "Springer-Verlag" (not "Springer")',
        'status': 'checked',
        "rules": ('JSS-NAME-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-052',
        'source': 'style_guide',
        'section': '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        'provision': 'MUST: "John Wiley & Sons" (not "Wiley" / "John Wiley & Sons Inc.")',
        'status': 'checked',
        "rules": ('JSS-NAME-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-053',
        'source': 'style_guide',
        'section': '#my-latex-paper-does-not-compile-when-there-is-jss-markup-in-section-titles-what-should-i-do',
        'provision': 'SHOULD: Section titles containing markup supply a plain-text shim via `\\section[plain]{markup}` for PDF bookmarks',
        'status': 'checked',
        "rules": ('JSS-MARKUP-004',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-054',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': 'MUST: Use "Section x.y" (not "Subsection x.y") when referring to subsections',
        'status': 'checked',
        "rules": ('JSS-XREF-003',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-055',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': 'MUST: "e.g.", "i.e." are followed by a comma to prevent LaTeX from interpreting the period as a sentence end',
        'status': 'checked',
        "rules": ('JSS-HOUSE-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-056',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': 'MUST: "$p$~value", "$t$~statistic", etc. have no hyphen and a tie `~` between symbol and noun',
        'status': 'checked',
        "rules": ('JSS-OPER-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-057',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': "MUST: Use `\\top` (not `'` or `T`) for the transpose symbol (`X^\\top`)",
        'status': 'checked',
        "rules": ('JSS-OPER-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-058',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': 'MUST: In R-related manuscripts, first argument of `data()` and `library()` is quoted (`library("foo")`)',
        'status': 'checked',
        "rules": ('JSS-CODE-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-059',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': 'MUST: Book editions are indicated as 2nd, 3rd, …',
        'status': 'checked',
        "rules": ('JSS-HOUSE-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-060',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': 'SHOULD: Prefer `Equation~\\ref{...}` (capitalised) over bare `(\\ref{...})` when referring to equations, except when reference count is large',
        'status': 'checked',
        "rules": ('JSS-XREF-002',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'SG-061',
        'source': 'style_guide',
        'section': '#miscellaneous',
        'provision': 'Cross-reference nouns are spelled out (Figure, Section, Table), not abbreviated',
        'status': 'checked',
        "rules": ('JSS-XREF-007',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'AI-001',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'MUST: Manuscripts are written in English using LaTeX',
        'status': 'checked',
        "rules": ('JSS-PRE-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'AI-002',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'MUST: JSS Style Guide is followed (delegates to §1.3)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'meta/delegation, see §1.3 coverage',
    }),
    MappingProxyType({
        'id': 'AI-003',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'MUST: Only PDF files can be submitted (submission format — not linter-checkable from `.tex`)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-004',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'Implicit: Authors are responsible for appropriate format (meta-rule — delegates to the other rules)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-005',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'Implicit: Non-compliant manuscripts are returned (meta-consequence, not a lint rule)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-006',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'SHOULD (advisory): Find a local LaTeX expert for assistance (meta-advice)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-007',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'NOTE: Manuscripts over 30 pages have longer review times (informational, not normative)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-008',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'MUST: All figures, tables, and output are fully reproducible on ≥1 platform (cannot be verified from `.tex` alone)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-009',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'MUST: Platform dependencies indicated with the submission (submission metadata)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-010',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'MUST: Random seed initialised when results depend on simulation',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'requires inspecting the replication script, not just the manuscript; deferred (candidate for eval-side checks)',
    }),
    MappingProxyType({
        'id': 'AI-011',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'SHOULD: Reproducibility is demonstrated by a standalone replication script (separate file, not the manuscript)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-012',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'SHOULD: Replication completes in ~1 hour on a regular PC (runtime claim)',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-013',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'SHOULD (advisory): If replication is slow/specialised, supply a proxy script',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-014',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': 'SHOULD (advisory): Provide an output file showing replication results',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-015',
        'source': 'author_instructions',
        'section': '#manuscript-preparation',
        'provision': "SHOULD: For R submissions, provide `code.html` via `knitr::spin('code.R')` including `sessionInfo()`",
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-016',
        'source': 'author_instructions',
        'section': '#requirements',
        'provision': 'MUST: PDF manuscript in JSS style is a required attachment',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-017',
        'source': 'author_instructions',
        'section': '#requirements',
        'provision': 'MUST: Replication materials are a required attachment',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-018',
        'source': 'author_instructions',
        'section': '#requirements',
        'provision': 'MUST: Large attachments are explained and linked',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-019',
        'source': 'author_instructions',
        'section': '#software-preparation',
        'provision': 'MUST: Source code is submitted as ASCII files',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-020',
        'source': 'author_instructions',
        'section': '#software-preparation',
        'provision': 'SHOULD: Code is readable and commented',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-021',
        'source': 'author_instructions',
        'section': '#software-preparation',
        'provision': 'HARD LIMIT: Max upload size 50 MB',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-022',
        'source': 'author_instructions',
        'section': '#software-preparation',
        'provision': 'MUST: Code includes GPL-2 / GPL-3 / GPL-compatible licence',
        'status': 'out_of_scope',
        "rules": (),
        "reason": 'not checkable from the manuscript source',
    }),
    MappingProxyType({
        'id': 'AI-023',
        'source': 'author_instructions',
        'section': 'internal',
        'provision': "A multi-file manuscript's \\input / \\include / \\subfile / \\bibliography graph is acyclic",
        'status': 'checked',
        "rules": ('JSS-PROJECT-001',),
        "reason": '',
    }),
    MappingProxyType({
        'id': 'AI-024',
        'source': 'author_instructions',
        'section': 'internal',
        'provision': 'Every \\input / \\include / \\subfile / \\bibliography target resolves to a file that exists',
        'status': 'checked',
        "rules": ('JSS-PROJECT-002',),
        "reason": '',
    }),
)

# Rollout order (from catalogue.yaml top-level categories field).
ROLLOUT_ORDER: tuple[str, ...] = (
    'preamble',
    'structure',
    'markup',
    'citations',
    'references',
    'bibtex',
    'naming',
    'capitalization',
    'typography',
    'abbreviations',
    'code_style',
    'code_width',
    'operators',
    'crossrefs',
    'house_style',
    'project',
)
