# AUTO-GENERATED from specs/003-jss-rule-catalogue/catalogue.yaml.
# Do not edit by hand; run `python -m tools.generate_catalogue_data`.

from __future__ import annotations

from collections.abc import Mapping
from types import MappingProxyType

from texlint.api import Severity

# One entry per active rule in catalogue.yaml.
RULES: Mapping[str, Mapping[str, object]] = MappingProxyType({
    'JSS-PRE-001': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'Document class must be jss with a valid class option (article, codesnippet, bookreview, softwarereview)',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:37',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'Document class must be jss with a valid class option (article, codesnippet, bookreview, softwarereview).',
    }),
    'JSS-PRE-002': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'Preamble defines \\Address{} with author affiliation and contact',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Address',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'Preamble defines \\Address{} with author affiliation and contact.',
    }),
    'JSS-PRE-003': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'When \\title{} contains LaTeX markup, preamble also defines \\Plaintitle{} with the markup-free form',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plaintitle',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'When \\title{} contains LaTeX markup, preamble also defines \\Plaintitle{} with the markup-free form.',
    }),
    'JSS-PRE-004': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": '\\Abstract{} is present and overrides the sentinel placeholder from jss.cls',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:120',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": '\\Abstract{} is present and overrides the sentinel placeholder from jss.cls.',
    }),
    'JSS-PRE-005': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": '\\Keywords{} is present and overrides the sentinel placeholder from jss.cls',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:197',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": '\\Keywords{} is present and overrides the sentinel placeholder from jss.cls.',
    }),
    'JSS-PRE-006': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.WARNING,
        "message_template": '\\Plaintitle, \\Plainauthor, \\Plainkeywords contain no LaTeX markup (PDF metadata must be plain text)',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plaintitle',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": '\\Plaintitle, \\Plainauthor, \\Plainkeywords contain no LaTeX markup (PDF metadata must be plain text).',
    }),
    'JSS-PRE-007': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'When \\author{} contains LaTeX markup, preamble also defines \\Plainauthor{} with the markup-free form',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plainauthor',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'When \\author{} contains LaTeX markup, preamble also defines \\Plainauthor{} with the markup-free form.',
    }),
    'JSS-PRE-008': MappingProxyType({
        "category": 'preamble',
        "severity": Severity.ERROR,
        "message_template": 'When \\Keywords{} contains LaTeX markup, preamble also defines \\Plainkeywords{} with the markup-free form',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\Plainkeywords',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.1 Preamble',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#preamble',
        "explanation": 'When \\Keywords{} contains LaTeX markup, preamble also defines \\Plainkeywords{} with the markup-free form.',
    }),
    'JSS-STRUCT-001': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Document ends with a summary / discussion section before the bibliography',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:378',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Document ends with a summary / discussion section before the bibliography.',
    }),
    'JSS-STRUCT-002': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Acknowledgments section uses American spelling (not "Acknowledgements")',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:407',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Acknowledgments section uses American spelling (not "Acknowledgements").',
    }),
    'JSS-STRUCT-003': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Appendix sections have proper titles instead of a bare "Appendix"',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:438',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Appendix sections have proper titles instead of a bare "Appendix".',
    }),
    'JSS-STRUCT-004': MappingProxyType({
        "category": 'structure',
        "severity": Severity.ERROR,
        "message_template": 'References are declared via \\bibliography{} rather than a hand-written thebibliography environment',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'References are declared via \\bibliography{} rather than a hand-written thebibliography environment.',
    }),
    'JSS-STRUCT-005': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": '\\author{} separates authors with \\And or \\AND (not lowercase \\and)',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:22',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": '\\author{} separates authors with \\And or \\AND (not lowercase \\and).',
    }),
    'JSS-STRUCT-006': MappingProxyType({
        "category": 'structure',
        "severity": Severity.WARNING,
        "message_template": 'Appendix follows the bibliography with a \\newpage (or \\clearpage) separator',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:430',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§2.2 Structure',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#structure',
        "explanation": 'Appendix follows the bibliography with a \\newpage (or \\clearpage) separator.',
    }),
    'JSS-MARKUP-001': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Programming-language names in prose are wrapped in \\proglang{}',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\proglang',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "confidence": 'medium',
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Programming-language names in prose are wrapped in \\proglang{}.',
    }),
    'JSS-MARKUP-002': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Software-package names in prose are wrapped in \\pkg{}',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\pkg',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Software-package names in prose are wrapped in \\pkg{}.',
    }),
    'JSS-MARKUP-003': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Inline function, argument, command names, and R sentinel values are wrapped in \\code{}',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:\\code',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Inline function, argument, and command names — and bare R sentinel values such as NULL, NA, TRUE, FALSE — are wrapped in \\code{}.',
    }),
    'JSS-MARKUP-004': MappingProxyType({
        "category": 'markup',
        "severity": Severity.WARNING,
        "message_template": 'Section titles containing markup supply a plain-text shim via \\section[plain]{markup}',
        "authority": 'style_guide',
        "authority_ref": '#my-latex-paper-does-not-compile-when-there-is-jss-markup-in-section-titles-what-should-i-do',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.1 Markup',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#markup',
        "explanation": 'Section titles containing markup supply a plain-text shim via \\section[plain]{markup}.',
    }),
    'JSS-CITE-002': MappingProxyType({
        "category": 'citations',
        "severity": Severity.WARNING,
        "message_template": 'First occurrence of a software package has a citation within the same paragraph',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "confidence": 'medium',
        "guide_section": '§3.2 Citations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#citations',
        "explanation": 'First occurrence of a software package has a citation within the same paragraph. See §3.2 Citations.',
    }),
    'JSS-CITE-003': MappingProxyType({
        "category": 'citations',
        "severity": Severity.WARNING,
        "message_template": 'Avoid bracket-in-bracket citation forms like (\\cite{...}); use \\citep{...} instead',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-different-cite-citet-citep-commands-about',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§3.2 Citations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#citations',
        "explanation": 'Avoid bracket-in-bracket citation forms like (\\cite{...}); use \\citep{...} instead.',
    }),
    'JSS-CITE-004': MappingProxyType({
        "category": 'citations',
        "severity": Severity.WARNING,
        "message_template": 'Citations use natbib commands (\\cite, \\citet, \\citep, \\citealp) rather than hardcoded author-year text',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:62',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§3.2 Citations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#citations',
        "explanation": 'Citations use natbib commands (\\cite, \\citet, \\citep, \\citealp) rather than hardcoded author-year text.',
    }),
    'JSS-REFS-001': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'BibTeX entries carry a year field so natbib author-year citations render correctly',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX entries carry a year field so natbib author-year citations render correctly.',
    }),
    'JSS-REFS-003': MappingProxyType({
        "category": 'references',
        "severity": Severity.INFO,
        "message_template": 'BibTeX entries include a doi field where one is available (advisory)',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:421',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX entries include a doi field where one is available (advisory).',
    }),
    'JSS-REFS-004': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'BibTeX titles use JSS markup (\\proglang, \\pkg, \\code) for language and package names',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX titles use JSS markup (\\proglang, \\pkg, \\code) for language and package names.',
    }),
    'JSS-REFS-005': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'Journal titles in BibTeX entries are not abbreviated',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:473',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'Journal titles in BibTeX entries are not abbreviated.',
    }),
    'JSS-REFS-006': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'BibTeX titles are in title style — loose heuristic (flags lowercase first word or unusual mixed case)',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'BibTeX titles are in title style — loose heuristic (flags lowercase first word or unusual mixed case).',
    }),
    'JSS-REFS-007': MappingProxyType({
        "category": 'references',
        "severity": Severity.WARNING,
        "message_template": 'Journal titles in BibTeX entries are in title case',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:473',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§3.3 References',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#references',
        "explanation": 'Journal titles in BibTeX entries are in title case.',
    }),
    'JSS-BIBTEX-001': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'Every BibTeX entry has a non-empty citation key',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'Every BibTeX entry has a non-empty citation key.',
    }),
    'JSS-BIBTEX-002': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'BibTeX citation keys are unique within the database',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'BibTeX citation keys are unique within the database.',
    }),
    'JSS-BIBTEX-003': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'BibTeX entries carry the fields required for their entry type (article, book, inproceedings, …)',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'BibTeX entries carry the fields required for their entry type (article, book, inproceedings, …).',
    }),
    'JSS-BIBTEX-004': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.WARNING,
        "message_template": 'Entries with 6+ authors use \\shortcites{} or the shortnames class option is enabled',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:45',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'Entries with 6+ authors use \\shortcites{} or the shortnames class option is enabled.',
    }),
    'JSS-BIBTEX-005': MappingProxyType({
        "category": 'bibtex',
        "severity": Severity.ERROR,
        "message_template": 'No BibTeX field key is repeated within a single entry',
        "authority": 'style_guide',
        "authority_ref": '#how-to-cite-r-packages',
        "inspects": ('bib_files',),
        "auto_fixable": False,
        "guide_section": '§5.1 Bibliography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#bibliography',
        "explanation": 'No BibTeX field key is repeated within a single entry.',
    }),
    'JSS-NAME-001': MappingProxyType({
        "category": 'naming',
        "severity": Severity.WARNING,
        "message_template": 'Programming-language names use their canonical capitalisation',
        "authority": 'style_guide',
        "authority_ref": '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§6.1 Naming',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#naming',
        "explanation": 'Programming-language names use their canonical capitalisation.',
    }),
    'JSS-NAME-002': MappingProxyType({
        "category": 'naming',
        "severity": Severity.WARNING,
        "message_template": 'Publisher and journal names follow JSS conventions (e.g., "Springer-Verlag", "The Annals of Statistics")',
        "authority": 'style_guide',
        "authority_ref": '#which-naming-conventions-are-used-for-software-journal-and-publisher-names-in-jss',
        "inspects": ('bib_files',),
        "auto_fixable": True,
        "guide_section": '§6.1 Naming',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#naming',
        "explanation": 'Publisher and journal names follow JSS conventions (e.g., "Springer-Verlag", "The Annals of Statistics").',
    }),
    'JSS-CAP-001': MappingProxyType({
        "category": 'capitalization',
        "severity": Severity.WARNING,
        "message_template": '\\title{} is in title style (principal words capitalised)',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§6.2 Capitalisation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#capitalisation',
        "explanation": '\\title{} is in title style (principal words capitalised).',
    }),
    'JSS-CAP-002': MappingProxyType({
        "category": 'capitalization',
        "severity": Severity.WARNING,
        "message_template": 'Section titles are in sentence style (first word capitalised; others lowercase except proper names)',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "confidence": 'medium',
        "guide_section": '§6.2 Capitalisation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#capitalisation',
        "explanation": 'Section titles are in sentence style (first word capitalised; others lowercase except proper names).',
    }),
    'JSS-CAP-004': MappingProxyType({
        "category": 'capitalization',
        "severity": Severity.WARNING,
        "message_template": '\\Keywords{} is comma-separated and in sentence case',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:48',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§6.2 Capitalisation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#capitalisation',
        "explanation": '\\Keywords{} is comma-separated and in sentence case.',
    }),
    'JSS-TYPO-001': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": 'Figure and table captions end with a period',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": 'Figure and table captions end with a period.',
    }),
    'JSS-TYPO-002': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": 'Figure / table captions avoid emphasis macros wrapping the whole caption (\\emph, \\textbf, \\textit on full caption)',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": 'Figure / table captions avoid emphasis macros wrapping the whole caption (\\emph, \\textbf, \\textit on full caption).',
    }),
    'JSS-TYPO-003': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": 'Tables do not use footnote-style annotations; annotations go in the caption',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": 'Tables do not use footnote-style annotations; annotations go in the caption.',
    }),
    'JSS-TYPO-004': MappingProxyType({
        "category": 'typography',
        "severity": Severity.WARNING,
        "message_template": '\\caption{} appears after the figure / table content, not before',
        "authority": 'style_guide',
        "authority_ref": '#how-to-format-figuretable-captions',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.3 Typography',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#typography',
        "explanation": '\\caption{} appears after the figure / table content, not before.',
    }),
    'JSS-ABBR-001': MappingProxyType({
        "category": 'abbreviations',
        "severity": Severity.WARNING,
        "message_template": 'Abbreviations are in uppercase without periods or additional formatting',
        "authority": 'style_guide',
        "authority_ref": '#how-should-abbrevations-be-formatted',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§6.3 Abbreviations',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#abbreviations',
        "explanation": 'Abbreviations are in uppercase without periods or additional formatting.',
    }),
    'JSS-CODE-001': MappingProxyType({
        "category": 'code_style',
        "severity": Severity.WARNING,
        "message_template": 'Verbatim / CodeInput blocks do not contain comments; comments belong in the surrounding LaTeX text',
        "authority": 'style_guide',
        "authority_ref": '#how-should-code-be-formatted-in-the-manuscript',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.2 Code style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#code-style',
        "explanation": 'Verbatim / CodeInput blocks do not contain comments; comments belong in the surrounding LaTeX text.',
    }),
    'JSS-CODE-002': MappingProxyType({
        "category": 'code_style',
        "severity": Severity.WARNING,
        "message_template": 'R library() and data() calls quote their first argument',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.2 Code style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#code-style',
        "explanation": 'R library() and data() calls quote their first argument.',
    }),
    'JSS-CODE-003': MappingProxyType({
        "category": 'code_style',
        "severity": Severity.WARNING,
        "message_template": 'Code samples use spaces around operators and after commas',
        "authority": 'style_guide',
        "authority_ref": '#how-should-code-be-formatted-in-the-manuscript',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.2 Code style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#code-style',
        "explanation": 'Code samples use spaces around operators and after commas.',
    }),
    'JSS-WIDTH-001': MappingProxyType({
        "category": 'code_width',
        "severity": Severity.WARNING,
        "message_template": 'Code input / output inside Sinput / CodeInput / CodeOutput environments fits within the configured column limit',
        "authority": 'style_guide',
        "authority_ref": '#how-should-code-be-formatted-in-the-manuscript',
        "inspects": ('raw_source',),
        "auto_fixable": False,
        "guide_section": '§7.1 Line width',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#line-width',
        "explanation": 'Code input / output inside Sinput / CodeInput / CodeOutput environments fits within the configured column limit.',
    }),
    'JSS-OPER-001': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Symbol-plus-noun constructs like p-value and t-statistic are typeset as $p$~value and $t$~statistic (tie, no hyphen)',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Symbol-plus-noun constructs like p-value and t-statistic are typeset as $p$~value and $t$~statistic (tie, no hyphen).',
    }),
    'JSS-OPER-002': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Transpose is typeset with \\top rather than a superscript prime or literal T',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Transpose is typeset with \\top rather than a superscript prime or literal T.',
    }),
    'JSS-OPER-003': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Display equations have no blank lines immediately before or after (use % to suppress paragraph breaks)',
        "authority": 'article_tex',
        "authority_ref": 'article.tex:154',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Display equations have no blank lines immediately before or after (use % to suppress paragraph breaks).',
    }),
    'JSS-OPER-004': MappingProxyType({
        "category": 'operators',
        "severity": Severity.WARNING,
        "message_template": 'Expectation / variance / covariance / probability use jss.cls shortcuts \\E, \\VAR, \\COV, \\Prob',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:484',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.4 Mathematical notation',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#mathematical-notation',
        "explanation": 'Expectation / variance / covariance / probability use jss.cls shortcuts \\E, \\VAR, \\COV, \\Prob.',
    }),
    'JSS-XREF-001': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Figures and tables are referenced via \\ref{} rather than by manual numbering',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Figures and tables are referenced via \\ref{} rather than by manual numbering (e.g. "Figure 2").',
    }),
    'JSS-XREF-002': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.INFO,
        "message_template": 'Equation references prefer Equation~\\ref{...} (capitalised) over bare (\\ref{...}) or \\eqref{...}',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Equation references prefer Equation~\\ref{...} (capitalised) over bare (\\ref{...}) or \\eqref{...}; both \\eqref and (\\ref) render as the parenthesised form reviewers discourage.',
    }),
    'JSS-XREF-003': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Cross-references to subsections use "Section x.y" rather than "Subsection x.y"',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Cross-references to subsections use "Section x.y" rather than "Subsection x.y".',
    }),
    'JSS-XREF-004': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.INFO,
        "message_template": 'Numbered equations carry \\label{} and are referenced from the text',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Numbered equations carry \\label{} and are referenced from the text.',
    }),
    'JSS-XREF-005': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Figures and tables carry \\label{} and are referenced from the text',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Figures and tables carry \\label{} and are referenced from the text.',
    }),
    'JSS-XREF-006': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.WARNING,
        "message_template": 'Figure and table floats carry a \\caption{}',
        "authority": 'style_guide',
        "authority_ref": '#what-are-the-most-important-style-guidelines-in-jss',
        "inspects": ('tex_files',),
        "auto_fixable": False,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": 'Figure and table floats carry a \\caption{} so they are numbered and can be referenced from the text.',
    }),
    'JSS-XREF-007': MappingProxyType({
        "category": 'crossrefs',
        "severity": Severity.INFO,
        "message_template": 'Cross-reference nouns are spelled out (Figure/Section/Table), not abbreviated (Fig./Sec./Tab.)',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§4.5 Cross-references',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#cross-references',
        "explanation": "Cross-reference nouns are spelled out (Figure/Section/Table), not abbreviated (Fig./Sec./Tab.); the figure/section/table analogue of JSS-XREF-002's Eq. -> Equation rule.",
    }),
    'JSS-HOUSE-001': MappingProxyType({
        "category": 'house_style',
        "severity": Severity.WARNING,
        "message_template": '"e.g." and "i.e." are followed by a comma so LaTeX does not treat the period as a sentence end',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§8.1 House style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#house-style',
        "explanation": '"e.g." and "i.e." are followed by a comma so LaTeX does not treat the period as a sentence end.',
    }),
    'JSS-HOUSE-002': MappingProxyType({
        "category": 'house_style',
        "severity": Severity.WARNING,
        "message_template": 'Book editions are indicated as 2nd, 3rd, etc., not as "second" or "2e"',
        "authority": 'style_guide',
        "authority_ref": '#miscellaneous',
        "inspects": ('bib_files',),
        "auto_fixable": True,
        "guide_section": '§8.1 House style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#house-style',
        "explanation": 'Book editions are indicated as 2nd, 3rd, etc., not as "second" or "2e".',
    }),
    'JSS-HOUSE-003': MappingProxyType({
        "category": 'house_style',
        "severity": Severity.INFO,
        "message_template": 'Preamble avoids loading LaTeX packages that jss.cls already provides (graphicx, xcolor, ae, fancyvrb, hyperref)',
        "authority": 'jss_cls',
        "authority_ref": 'jss.cls:54',
        "inspects": ('tex_files',),
        "auto_fixable": True,
        "guide_section": '§8.1 House style',
        "guide_url": 'https://www.jstatsoft.org/about/submissions#house-style',
        "explanation": 'Preamble avoids loading LaTeX packages that jss.cls already provides (graphicx, xcolor, ae, fancyvrb, hyperref).',
    }),
})

RETIRED_RULE_IDS: frozenset[str] = frozenset({
    'JSS-ABBR-002',
    'JSS-CAP-003',
    'JSS-CITE-001',
    'JSS-REFS-002',
})

# Rollout order (from catalogue.yaml top-level categories field).
ROLLOUT_ORDER: tuple[str, ...] = (
    'preamble',
    'structure',
    'markup',
    'citations',
    'references',
    'bibtex',
    'naming',
    'capitalization',
    'typography',
    'abbreviations',
    'code_style',
    'code_width',
    'operators',
    'crossrefs',
    'house_style',
)
