"""Spec 010 — `jss-lint init` Python API.

CLI integration follows after the Click sub-group migration ships
(spec 009 deferred); this module is the seam.
"""

from __future__ import annotations

import os
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from texlint.api import ComplianceReport, Violation


@dataclass(frozen=True)
class InitResult:
    config_path: Path
    wrote: bool
    contents: str
    must_fix_count: int
    suppressed_count: int
    total_violations: int


def _render_toml(
    *,
    journal: str,
    ignored_rules: Iterable[tuple[str, str]],
    threshold: float,
) -> str:
    """Hand-rolled TOML so we don't need `tomli_w` as a runtime dep
    just for spec 010 v1.

    `ignored_rules` is an iterable of (rule_id, comment) pairs.
    """
    today = date.today().isoformat()
    lines = [
        f'journal = "{journal}"',
        "",
        f"# auto-generated by `jss-lint init` on {today}",
        f"# threshold = {threshold:.2f} (matches Constitution §VI)",
        "",
        "ignore_rules = [",
    ]
    for rule_id, comment in sorted(ignored_rules, key=lambda x: x[0]):
        lines.append(f"  # {rule_id}: {comment}")
        lines.append(f'  "{rule_id}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def _atomic_write(target: Path, contents: str) -> None:
    parent = target.parent
    fd, tmp_path = tempfile.mkstemp(prefix=".jss-lint.", dir=parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(contents)
            f.flush()
            try:
                os.fsync(f.fileno())
            except OSError:  # pragma: no cover
                pass
        os.replace(tmp_path, target)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:  # pragma: no cover
            pass
        raise


class InitRefusedError(RuntimeError):
    """Raised when `.jss-lint.toml` exists and `--force` was not set."""


def run(
    target_dir: Path,
    *,
    report: ComplianceReport,
    force: bool = False,
    dry_run: bool = False,
    threshold: float = 0.90,
    journal: str = "jss",
) -> InitResult:
    """Build (and optionally write) a `.jss-lint.toml` for a manuscript.

    *target_dir* is the directory in which `.jss-lint.toml` will live.
    *report* is the read-only lint report against the manuscript.
    *threshold* is currently informational; precision-DB-aware
    suppressions are a follow-up.
    """
    if not 0.0 <= threshold <= 1.0:
        raise ValueError(f"--threshold must be between 0 and 1; got {threshold}")

    config_path = target_dir / ".jss-lint.toml"
    if not dry_run and config_path.exists() and not force:
        raise InitRefusedError(
            f"refusing to overwrite {config_path}; pass --force to overwrite"
        )

    by_rule: dict[str, list[Violation]] = {}
    for v in report.violations:
        by_rule.setdefault(v.rule_id, []).append(v)

    # v1: no precision-DB integration. The generated config has
    # `ignore_rules = []` and the user can hand-edit. Future spec
    # extends this to query the precision-history DB.
    ignored: list[tuple[str, str]] = []

    contents = _render_toml(
        journal=journal,
        ignored_rules=ignored,
        threshold=threshold,
    )

    if not dry_run:
        _atomic_write(config_path, contents)
        wrote = True
    else:
        wrote = False

    return InitResult(
        config_path=config_path,
        wrote=wrote,
        contents=contents,
        must_fix_count=len(by_rule),
        suppressed_count=len(ignored),
        total_violations=len(report.violations),
    )
