"""Spec 010 — `jss-lint init` Python API.

CLI integration shipped via the spec-009/010 Click subcommand batch.
This module is the engine seam.

Spec 010 follow-up (this version): precision-DB-aware suppression.
When ``eval/precision-history.db`` is available locally, the
generated ``.jss-lint.toml`` suppresses any rule whose corpus-wide
precision (from the latest iteration) falls below ``--threshold``
(default 0.90, matching Constitution §VI). The generated config's
``ignore_rules`` list is annotated with the precision value and
the iteration label so the user can audit each suppression.
"""

from __future__ import annotations

import os
import sqlite3
import tempfile
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from texlint.api import ComplianceReport, Violation

# Default DB location — relative to repo root. Callers may override via
# the ``precision_db_path`` argument to :func:`run`.
_DEFAULT_DB_PATH = Path("eval") / "precision-history.db"


@dataclass(frozen=True)
class InitResult:
    config_path: Path
    wrote: bool
    contents: str
    must_fix_count: int
    suppressed_count: int
    total_violations: int


def _read_precision_db(
    db_path: Path,
) -> tuple[dict[str, float], str | None]:
    """Read the latest per-rule precision values from the eval-jss DB.

    Returns ``({rule_id: precision}, label)``. ``label`` is the
    iteration's human-readable tag (e.g. ``"iter-78-convergence"``)
    so the generated TOML's comments can cite it. Returns ``({}, None)``
    when the DB is missing or unreadable — the caller treats that as
    "no precision data available; no auto-suppressions".

    The DB schema lives in ``eval/schema.sql`` (spec 002). Only rules
    with a non-NULL ``precision`` value in the latest ``full``-scope
    run participate; rules without measured precision (status
    ``NOT MEASURED``) are silently skipped.
    """
    if not db_path.is_file():
        return {}, None
    try:
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    except sqlite3.OperationalError:  # pragma: no cover - permissions etc.
        return {}, None
    try:
        latest = conn.execute(
            "SELECT id, label FROM iterations ORDER BY id DESC LIMIT 1"
        ).fetchone()
        if latest is None:
            return {}, None
        latest_id, label = latest
        rows = conn.execute(
            "SELECT rule_id, precision FROM iteration_rule_stats "
            "WHERE iteration_id = ? AND scope = 'full' "
            "  AND precision IS NOT NULL",
            (latest_id,),
        ).fetchall()
    finally:
        conn.close()
    return {rid: float(p) for rid, p in rows}, label


def _render_toml(
    *,
    journal: str,
    ignored_rules: Iterable[tuple[str, str]],
    threshold: float,
) -> str:
    """Hand-rolled TOML so we don't need `tomli_w` as a runtime dep
    just for spec 010 v1.

    `ignored_rules` is an iterable of (rule_id, comment) pairs.
    """
    today = date.today().isoformat()
    lines = [
        f'journal = "{journal}"',
        "",
        f"# auto-generated by `jss-lint init` on {today}",
        f"# threshold = {threshold:.2f} (matches Constitution §VI)",
        "",
        "ignore_rules = [",
    ]
    for rule_id, comment in sorted(ignored_rules, key=lambda x: x[0]):
        lines.append(f"  # {rule_id}: {comment}")
        lines.append(f'  "{rule_id}",')
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


def _atomic_write(target: Path, contents: str) -> None:
    parent = target.parent
    fd, tmp_path = tempfile.mkstemp(prefix=".jss-lint.", dir=parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(contents)
            f.flush()
            try:
                os.fsync(f.fileno())
            except OSError:  # pragma: no cover
                pass
        os.replace(tmp_path, target)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:  # pragma: no cover
            pass
        raise


class InitRefusedError(RuntimeError):
    """Raised when `.jss-lint.toml` exists and `--force` was not set."""


def run(
    target_dir: Path,
    *,
    report: ComplianceReport,
    force: bool = False,
    dry_run: bool = False,
    threshold: float = 0.90,
    journal: str = "jss",
    precision_db_path: Path | None = None,
) -> InitResult:
    """Build (and optionally write) a `.jss-lint.toml` for a manuscript.

    *target_dir* is the directory in which `.jss-lint.toml` will live.
    *report* is the read-only lint report against the manuscript.

    *precision_db_path* points at the spec-002 eval-jss SQLite file.
    When ``None`` (default) the function tries
    ``<target_dir>/eval/precision-history.db`` and the canonical
    repo-relative ``eval/precision-history.db``. When a DB is found,
    every rule whose latest measured precision falls below
    ``threshold`` is added to ``ignore_rules`` with an inline comment
    citing the precision value + iteration label. When no DB is
    found the generated config has an empty ``ignore_rules``.
    """
    if not 0.0 <= threshold <= 1.0:
        raise ValueError(f"--threshold must be between 0 and 1; got {threshold}")

    config_path = target_dir / ".jss-lint.toml"
    if not dry_run and config_path.exists() and not force:
        raise InitRefusedError(
            f"refusing to overwrite {config_path}; pass --force to overwrite"
        )

    by_rule: dict[str, list[Violation]] = {}
    for v in report.violations:
        by_rule.setdefault(v.rule_id, []).append(v)

    # Resolve the precision DB path. Order: explicit arg → target_dir
    # sibling → repo-relative default (relative to the current working
    # directory at call time).
    candidates: list[Path] = []
    if precision_db_path is not None:
        candidates.append(precision_db_path)
    else:
        candidates.append(target_dir / "eval" / "precision-history.db")
        candidates.append(_DEFAULT_DB_PATH)
    precision_per_rule: dict[str, float] = {}
    db_label: str | None = None
    for candidate in candidates:
        if candidate.is_file():
            precision_per_rule, db_label = _read_precision_db(candidate)
            if precision_per_rule:
                break

    ignored: list[tuple[str, str]] = []
    if precision_per_rule:
        for rid, precision in precision_per_rule.items():
            if precision < threshold:
                comment = (
                    f"precision {precision:.2f} (run {db_label}), "
                    f"below {threshold:.2f}"
                )
                ignored.append((rid, comment))
    # When the DB is missing or empty the loop above is a no-op and
    # `ignored` stays empty; this is the documented graceful path.

    contents = _render_toml(
        journal=journal,
        ignored_rules=ignored,
        threshold=threshold,
    )

    if not dry_run:
        _atomic_write(config_path, contents)
        wrote = True
    else:
        wrote = False

    return InitResult(
        config_path=config_path,
        wrote=wrote,
        contents=contents,
        must_fix_count=len(by_rule),
        suppressed_count=len(ignored),
        total_violations=len(report.violations),
    )
