"""Generate ``paper/generated/`` — every statistic the JSS paper cites.

Invoke from the repository root::

    python -m tools.generate_paper_stats          # write paper/generated/
    python -m tools.generate_paper_stats --check  # exit 1 if committed files drift
    python -m tools.generate_paper_stats --audit  # flag hard-coded numbers in paper.tex

No statistic in ``paper/paper.tex`` may be typed by hand: prose numbers
resolve through the ``\\Stat...`` macros in ``generated/stats.tex`` and
table bodies are ``\\input`` from ``generated/tab-*.tex``.  The single
source of truth is the pinned evaluation state below; the pin constants
are the only place to touch when re-freezing.

Follows the pattern of ``tools/generate_catalogue_data.py`` (AUTO-GENERATED
headers, atomic writes, ``--check`` drift gate).
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sqlite3
import subprocess
import sys
import tempfile
from collections import Counter
from pathlib import Path

import tomllib
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOGUE_YAML = REPO_ROOT / "specs" / "003-jss-rule-catalogue" / "catalogue.yaml"
HISTORY_DB = REPO_ROOT / "eval" / "precision-history.db"
MANIFEST_CSV = REPO_ROOT / "eval" / "corpus-manifest.csv"
GATE_EXCEPTIONS = REPO_ROOT / "eval" / "gate-exceptions.toml"
BENCHMARK_MD = REPO_ROOT / "eval" / "benchmark-results.md"
GOLD_SUMMARY_MD = REPO_ROOT / "eval" / "labeler-benchmark-summary.md"
NONR_SOURCES_MD = REPO_ROOT / "eval" / "non-cran-jss-sources.md"
OUTPUT_DIR = REPO_ROOT / "paper" / "generated"
PAPER_TEX = REPO_ROOT / "paper" / "paper.tex"

# --------------------------------------------------------------------------
# Pin constants — the ONLY values to touch when re-freezing the evaluation.
# The precision-history DB is append-only, so pinning an iteration label and
# a recall run timestamp makes regeneration byte-identical forever.
# --------------------------------------------------------------------------
PIN_ITERATION_LABEL = "post-code003-cli-flags"
PIN_RECALL_TS = "2026-07-11T21:23:39Z"
PIN_RECALL_HASH = "d5aab71bb82f97ee"
PIN_SCOPE = "full"
MIN_PLANTS = 10  # per-rule recall reported only at >= this many plants
PRECISION_GATE = 0.90
# Release-artifact facts (update at the pre-submission gate; see
# paper/revision-checklist.md items C1/C2).
REPO_URL = "https://github.com/kollerma/jss-style-checker-dev"
PYPI_NAME = "jss-style-checker"

_HEADER = (
    "%% AUTO-GENERATED by `python -m tools.generate_paper_stats`.\n"
    "%% Do not edit by hand. Pinned to precision iteration"
    f" `{PIN_ITERATION_LABEL}`\n"
    f"%% and recall run {PIN_RECALL_TS} (corpus {PIN_RECALL_HASH}).\n"
)


def _fmt_int(n: int) -> str:
    return f"{n:,}"


def _fmt_pct(x: float, digits: int = 1) -> str:
    return f"{100.0 * x:.{digits}f}\\%"


def _macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def _round_down(n: int, step: int = 50) -> int:
    return (n // step) * step


# --------------------------------------------------------------------------
# Data collection
# --------------------------------------------------------------------------


def load_catalogue() -> dict:
    with CATALOGUE_YAML.open("r", encoding="utf-8") as f:
        doc = yaml.safe_load(f)
    retired = set(doc.get("retired_rule_ids") or ())
    active = [r for r in doc["rules"] if r["rule_id"] not in retired]
    return {
        "doc": doc,
        "active": active,
        "retired": sorted(retired),
        "deterministic": sorted(doc.get("deterministic_rule_ids") or ()),
        "categories": list(doc["categories"]),
    }


def load_precision(db: sqlite3.Connection) -> dict:
    row = db.execute(
        "SELECT id, ts, corpus_size, tool_version FROM iterations WHERE label = ?",
        (PIN_ITERATION_LABEL,),
    ).fetchone()
    if row is None:
        raise SystemExit(
            f"error: no iteration labelled {PIN_ITERATION_LABEL!r} in {HISTORY_DB}"
        )
    it_id, ts, corpus_size, tool_version = row
    per_rule = db.execute(
        "SELECT rule_id, tp, fp FROM iteration_rule_stats"
        " WHERE iteration_id = ? AND scope = ? AND tp + fp > 0"
        " ORDER BY rule_id",
        (it_id, PIN_SCOPE),
    ).fetchall()
    n_iterations = db.execute("SELECT COUNT(*) FROM iterations").fetchone()[0]
    return {
        "iteration_id": it_id,
        "ts": ts,
        "corpus_size": corpus_size,
        "tool_version": tool_version,
        "per_rule": per_rule,
        "n_iterations": n_iterations,
    }


def load_recall(db: sqlite3.Connection) -> dict:
    rows = db.execute(
        "SELECT rule_id, tp, fn FROM recall_history"
        " WHERE run_timestamp = ? AND corpus_hash = ? ORDER BY rule_id",
        (PIN_RECALL_TS, PIN_RECALL_HASH),
    ).fetchall()
    if not rows:
        raise SystemExit(
            f"error: no recall run at {PIN_RECALL_TS} / {PIN_RECALL_HASH} in {HISTORY_DB}"
        )
    return {"per_rule": rows}


def load_manifest() -> dict:
    with MANIFEST_CSV.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))
    ext = Counter(
        Path(r["vignette_file"]).suffix.lower().lstrip(".") for r in rows
    )
    source = Counter(r["source"] for r in rows)
    return {"rows": rows, "ext": ext, "source": source}


def load_repo_langs() -> dict[str, tuple[str, bool]]:
    """repo -> (languages, non_r), from the "Corpus language classification"
    table in eval/non-cran-jss-sources.md (| Repo | Languages | Non-R |)."""
    langs: dict[str, tuple[str, bool]] = {}
    if not NONR_SOURCES_MD.exists():
        return langs
    in_section = False
    for line in NONR_SOURCES_MD.read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            in_section = line.strip() == "## Corpus language classification"
            continue
        if not in_section or not line.strip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) == 3 and "/" in cells[0] and cells[2] in ("yes", "no"):
            langs[cells[0]] = (cells[1], cells[2] == "yes")
    return langs


def classify_nonr(manifest: dict) -> dict:
    """Classify github-sourced corpus rows by manuscript language."""
    langs = load_repo_langs()
    nonr, r_lang, unknown = [], [], []
    lang_names: Counter[str] = Counter()
    for row in manifest["rows"]:
        if row["source"] != "github":
            continue
        entry = langs.get(row["source_id"])
        if entry is None:
            unknown.append(row["source_id"])
            continue
        lang, is_nonr = entry
        if is_nonr:
            nonr.append(row["source_id"])
            for part in lang.split("/"):
                if part.strip() != "R":
                    lang_names[part.strip()] += 1
        else:
            r_lang.append(row["source_id"])
    return {
        "nonr": sorted(nonr),
        "r": sorted(r_lang),
        "unknown": sorted(unknown),
        "langs": lang_names,
    }


def load_gate_exceptions() -> set[str]:
    with GATE_EXCEPTIONS.open("rb") as f:
        doc = tomllib.load(f)
    return {e["rule_id"] for e in doc.get("exceptions", ())}


def load_benchmark() -> dict:
    text = BENCHMARK_MD.read_text(encoding="utf-8")
    header = re.search(
        r"\*\*Papers:\*\*\s*(\d+)\s+\*\*Total wall \(parse\+lint\):\*\*\s*([\d.]+)\s*s"
        r"\s+\*\*Throughput:\*\*\s*([\d.]+)",
        text,
    )
    metrics = dict(re.findall(r"^\|\s*(mean|median|p95|min|max)\s*\|\s*([\d.]+)\s*\|", text, re.M))
    machine = re.search(r"^- Machine: (.+)$", text, re.M)
    if not header or "median" not in metrics:
        raise SystemExit(f"error: cannot parse {BENCHMARK_MD}")
    return {
        "papers": int(header.group(1)),
        "total_s": float(header.group(2)),
        "throughput": float(header.group(3)),
        "metrics": {k: float(v) for k, v in metrics.items()},
        "machine": machine.group(1).strip() if machine else "unknown",
    }


def load_gold_set_size() -> int:
    text = GOLD_SUMMARY_MD.read_text(encoding="utf-8")
    m = re.search(r"Gold set = \*\*([\d,]+) rows\*\*", text)
    if not m:
        raise SystemExit(f"error: cannot parse gold-set size from {GOLD_SUMMARY_MD}")
    return int(m.group(1).replace(",", ""))


def count_tests() -> int:
    out = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "tests"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    m = re.search(r"(\d+) tests? collected", out.stdout + out.stderr)
    if not m:
        tail = (out.stdout + out.stderr).strip().splitlines()[-3:]
        raise SystemExit("error: pytest --collect-only failed: " + " / ".join(tail))
    return int(m.group(1))


def count_commits() -> tuple[int, int]:
    total = int(
        subprocess.run(
            ["git", "rev-list", "--count", "HEAD"],
            cwd=REPO_ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    )
    ai = int(
        subprocess.run(
            ["git", "rev-list", "--count", "--grep=Co-Authored-By: Claude", "HEAD"],
            cwd=REPO_ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    )
    return total, ai


def count_specs() -> int:
    specs = REPO_ROOT / "specs"
    return sum(1 for p in specs.iterdir() if p.is_dir() and re.match(r"\d{3}-", p.name))


def tool_version() -> str:
    m = re.search(
        r'^version = "([^"]+)"',
        (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"),
        re.M,
    )
    assert m, "pyproject.toml version not found"
    return m.group(1)


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def render_stats(data: dict) -> str:
    cat = data["catalogue"]
    prec = data["precision"]
    rec = data["recall"]
    man = data["manifest"]
    nonr = data["nonr"]
    bench = data["benchmark"]
    exceptions = data["exceptions"]

    tp = sum(r[1] for r in prec["per_rule"])
    fp = sum(r[2] for r in prec["per_rule"])
    measured = len(prec["per_rule"])
    passing = sum(1 for _, t, f in prec["per_rule"] if t / (t + f) >= PRECISION_GATE)
    perfect = sum(1 for _, t, f in prec["per_rule"] if f == 0)

    rtp = sum(r[1] for r in rec["per_rule"])
    rfn = sum(r[2] for r in rec["per_rule"])
    scored = [(rid, t, f) for rid, t, f in rec["per_rule"] if t + f > 0]
    macro = sum(t / (t + f) for _, t, f in scored) / len(scored)
    thick = [(rid, t, f) for rid, t, f in scored if t + f >= MIN_PLANTS]
    perfect_recall = sum(1 for _, t, f in thick if f == 0)

    rnw = man["ext"].get("rnw", 0)
    rmd = man["ext"].get("rmd", 0)
    tex = man["ext"].get("tex", 0) + man["ext"].get("ltx", 0)

    out = [_HEADER, "%% Numbers — never type these by hand in paper.tex.\n"]
    m = out.append
    # Tool / repo facts
    m(_macro("StatToolVersion", data["tool_version"]))
    m(_macro("StatRuleCount", str(len(cat["active"]))))
    m(_macro("StatCategoryCount", str(len(cat["categories"]))))
    m(_macro("StatRetiredCount", str(len(cat["retired"]))))
    m(_macro("StatDeterministicCount", str(len(cat["deterministic"]))))
    m(_macro("StatSpecCount", str(data["n_specs"])))
    m(_macro("StatTestCount", _fmt_int(data["n_tests"])))
    m(_macro("StatCommitsApprox", _fmt_int(_round_down(data["n_commits"]))))
    m(_macro("StatAICommitsApprox", _fmt_int(_round_down(data["n_ai_commits"]))))
    # Corpus composition
    m(_macro("StatCorpusSize", str(prec["corpus_size"])))
    m(_macro("StatCorpusCran", str(man["source"].get("cran", 0))))
    m(_macro("StatCorpusGithub", str(man["source"].get("github", 0))))
    m(_macro("StatCorpusManual", str(man["source"].get("manual", 0))))
    m(_macro("StatCorpusRnw", str(rnw)))
    m(_macro("StatCorpusRmd", str(rmd)))
    m(_macro("StatCorpusTex", str(tex)))
    m(_macro("StatCorpusNonR", str(len(nonr["nonr"]))))
    langs = sorted(nonr["langs"], key=lambda k: (-nonr["langs"][k], k))
    m(_macro("StatCorpusNonRLangs", ", ".join(f"\\proglang{{{x}}}" for x in langs)))
    # Precision (pinned iteration)
    m(_macro("StatIterationCount", str(prec["n_iterations"])))
    m(_macro("StatPrecisionOverall", _fmt_pct(tp / (tp + fp))))
    m(_macro("StatPrecisionTP", _fmt_int(tp)))
    m(_macro("StatPrecisionFP", _fmt_int(fp)))
    m(_macro("StatPrecisionReviewed", _fmt_int(tp + fp)))
    m(_macro("StatRulesMeasured", str(measured)))
    m(_macro("StatRulesPassing", str(passing)))
    m(_macro("StatRulesPerfect", str(perfect)))
    m(_macro("StatGateExemptCount", str(len(exceptions))))
    m(_macro("StatGatePct", f"{PRECISION_GATE * 100:.0f}\\%"))
    # Recall (pinned run)
    m(_macro("StatRecallMicro", _fmt_pct(rtp / (rtp + rfn))))
    m(_macro("StatRecallMacro", _fmt_pct(macro)))
    m(_macro("StatRecallTP", _fmt_int(rtp)))
    m(_macro("StatRecallFN", _fmt_int(rfn)))
    m(_macro("StatRecallPlants", _fmt_int(rtp + rfn)))
    m(_macro("StatRecallRules", str(len(scored))))
    m(_macro("StatRecallThickRules", str(len(thick))))
    m(_macro("StatRecallPerfect", str(perfect_recall)))
    m(_macro("StatRecallMinPlants", str(MIN_PLANTS)))
    m(_macro("StatRecallCorpusPapers", str(data["n_recall_papers"])))
    # Labeling / methodology
    m(_macro("StatGoldSetSize", _fmt_int(data["gold_set_size"])))
    # Performance
    m(_macro("StatBenchPapers", str(bench["papers"])))
    m(_macro("StatBenchTotalSeconds", f"{bench['total_s']:.0f}"))
    m(_macro("StatBenchThroughput", f"{bench['throughput']:.1f}"))
    m(_macro("StatBenchMedianMs", f"{bench['metrics']['median'] * 1000:.0f}"))
    m(_macro("StatBenchPNinetyFiveMs", f"{bench['metrics']['p95'] * 1000:.0f}"))
    # Release artifacts (\urldef because \url{} cannot take a macro arg)
    m(f"\\urldef{{\\StatRepoUrl}}\\url{{{REPO_URL}}}\n")
    m(_macro("StatPyPIName", PYPI_NAME))
    # Provenance (printed in the reproducibility section)
    m(_macro("StatPinnedIteration", PIN_ITERATION_LABEL))
    m(_macro("StatPinnedIterationDate", prec["ts"].split("T")[0]))
    m(_macro("StatPinnedRecallRun", PIN_RECALL_TS.replace("T", " ").replace("Z", " UTC")))
    m(_macro("StatPinnedRecallHash", PIN_RECALL_HASH))
    return "".join(out)


def render_rule_summary(data: dict) -> str:
    """Per-category body rows: category, #rules, reviewed, precision."""
    cat = data["catalogue"]
    by_rule = {rid: (t, f) for rid, t, f in data["precision"]["per_rule"]}
    rows = []
    for category in cat["categories"]:
        rules = [r for r in cat["active"] if r["category"] == category]
        if not rules:
            continue
        tp = sum(by_rule.get(r["rule_id"], (0, 0))[0] for r in rules)
        fp = sum(by_rule.get(r["rule_id"], (0, 0))[1] for r in rules)
        prec = _fmt_pct(tp / (tp + fp)) if tp + fp else "---"
        pretty = category.replace("_", " ").capitalize()
        rows.append(
            f"{pretty} & {len(rules)} & {_fmt_int(tp + fp)} & {prec} \\\\\n"
        )
    # \bottomrule lives in the generated body: a booktabs rule may not
    # directly follow \input{} (misplaced \noalign).
    rows.append("\\bottomrule\n")
    return _HEADER + "".join(rows)


def render_precision_table(data: dict) -> str:
    exceptions = data["exceptions"]
    rows = []
    for rid, tp, fp in data["precision"]["per_rule"]:
        p = tp / (tp + fp)
        gate = "pass" if p >= PRECISION_GATE else (
            "exempt" if rid in exceptions else "FAIL"
        )
        rows.append(
            f"\\code{{{rid}}} & {_fmt_int(tp)} & {_fmt_int(fp)}"
            f" & {_fmt_pct(p)} & {gate} \\\\\n"
        )
    return _HEADER + "".join(rows)


def render_recall_table(data: dict) -> str:
    thick, thin_tp, thin_fn, thin_n = [], 0, 0, 0
    for rid, tp, fn in data["recall"]["per_rule"]:
        if tp + fn == 0:
            continue
        if tp + fn >= MIN_PLANTS:
            thick.append((rid, tp, fn))
        else:
            thin_tp, thin_fn, thin_n = thin_tp + tp, thin_fn + fn, thin_n + 1
    rows = [
        f"\\code{{{rid}}} & {_fmt_int(tp + fn)} & {_fmt_int(tp)}"
        f" & {_fmt_pct(tp / (tp + fn))} \\\\\n"
        for rid, tp, fn in thick
    ]
    if thin_n:
        rows.append("\\midrule\n")
        rows.append(
            f"{thin_n} rules below {MIN_PLANTS} plants (pooled)"
            f" & {_fmt_int(thin_tp + thin_fn)} & {_fmt_int(thin_tp)}"
            f" & {_fmt_pct(thin_tp / (thin_tp + thin_fn))} \\\\\n"
        )
    return _HEADER + "".join(rows)


def render_catalogue_table(data: dict) -> str:
    """Appendix body: every active rule with a \\hypertarget anchor."""
    cat = data["catalogue"]
    by_rule = {rid: (t, f) for rid, t, f in data["precision"]["per_rule"]}
    rows = []
    for category in cat["categories"]:
        rules = [r for r in cat["active"] if r["category"] == category]
        if not rules:
            continue
        pretty = category.replace("_", " ").capitalize()
        rows.append(
            f"\\multicolumn{{3}}{{l}}{{\\textbf{{{pretty}}}}} \\\\\n"
        )
        for r in sorted(rules, key=lambda r: int(r["rule_id"].rsplit("-", 1)[-1])):
            rid = r["rule_id"]
            desc = r["summary"] if "summary" in r else r["description"]
            desc = _tex_escape(desc.strip().rstrip("."))
            t, f = by_rule.get(rid, (0, 0))
            prec = _fmt_pct(t / (t + f)) if t + f else "---"
            rows.append(
                f"\\hypertarget{{rule:{rid}}}{{\\code{{{rid}}}}}"
                f" & {desc} & {prec} \\\\\n"
            )
        rows.append("\\addlinespace\n")
    return _HEADER + "".join(rows)


_TEX_ESCAPES = {
    "&": r"\&",
    "%": r"\%",
    "#": r"\#",
    "_": r"\_",
    "$": r"\$",
    "{": r"\{",
    "}": r"\}",
    "\\": r"\textbackslash{}",
    "~": r"\textasciitilde{}",
}


def _tex_escape(text: str) -> str:
    """Typeset a catalogue summary as plain text: macro mentions such as
    ``\\Address{}`` must be *displayed*, never executed."""
    text = re.sub(r'"([^"]*)"', r"``\1''", text)
    escaped = "".join(_TEX_ESCAPES.get(ch, ch) for ch in text)
    # Render macro mentions in code face: \textbackslash{}Foo -> \code{...}
    return re.sub(
        r"(\\textbackslash\{\}[A-Za-z@]+(?:\\\{\\\})?)",
        r"\\code{\1}",
        escaped,
    )


def render_benchmark_table(data: dict) -> str:
    b = data["benchmark"]
    rows = [
        f"Corpus size & {b['papers']} manuscripts \\\\\n",
        f"Total wall time (parse + lint) & {b['total_s']:.1f}\\,s \\\\\n",
        f"Throughput & {b['throughput']:.1f} manuscripts/s \\\\\n",
        f"Median per manuscript & {b['metrics']['median'] * 1000:.0f}\\,ms \\\\\n",
        f"95th percentile & {b['metrics']['p95'] * 1000:.0f}\\,ms \\\\\n",
        f"Maximum & {b['metrics']['max']:.2f}\\,s \\\\\n",
        "\\bottomrule\n",
    ]
    return _HEADER + "".join(rows)


# --------------------------------------------------------------------------
# Audit mode — no hard-coded statistics in paper.tex
# --------------------------------------------------------------------------

_AUDIT_ALLOW = re.compile(
    r"^(19|20)\d{2}$"      # years
    r"|^[0-3]?\d$"          # small enumerations / section-ish numbers (0–39)
    r"|^(30|50|70|80|90)$"  # page/width/gate conventions spelled in prose
)


def audit_paper() -> int:
    if not PAPER_TEX.exists():
        print(f"error: {PAPER_TEX} not found", file=sys.stderr)
        return 2
    findings: list[tuple[int, str, str]] = []
    for lineno, raw in enumerate(PAPER_TEX.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("%", 1)[0]
        if "\\Stat" in line or not line.strip():
            continue
        # skip pure-markup lines (labels, refs, geometry, includes)
        for num in re.findall(r"(?<![\w.\\{-])\d[\d,]*\.?\d*(?=\s*[%\\]?)", line):
            token = num.rstrip(".").replace(",", "")
            if not token or _AUDIT_ALLOW.match(token):
                continue
            findings.append((lineno, num, line.strip()[:90]))
    for lineno, num, ctx in findings:
        print(f"paper.tex:{lineno}: hard-coded number {num!r}: {ctx}")
    print(f"{len(findings)} finding(s)")
    return 1 if findings else 0


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------


def collect() -> dict:
    db = sqlite3.connect(HISTORY_DB)
    try:
        precision = load_precision(db)
        recall = load_recall(db)
    finally:
        db.close()
    manifest = load_manifest()
    n_recall_papers = sum(
        1
        for p in (REPO_ROOT / "eval" / "recall-corpus").iterdir()
        if p.is_dir()
    )
    n_total, n_ai = count_commits()
    return {
        "catalogue": load_catalogue(),
        "precision": precision,
        "recall": recall,
        "manifest": manifest,
        "nonr": classify_nonr(manifest),
        "exceptions": load_gate_exceptions(),
        "benchmark": load_benchmark(),
        "gold_set_size": load_gold_set_size(),
        "n_tests": count_tests(),
        "n_commits": n_total,
        "n_ai_commits": n_ai,
        "n_specs": count_specs(),
        "n_recall_papers": n_recall_papers,
        "tool_version": tool_version(),
    }


def render_all(data: dict) -> dict[str, str]:
    return {
        "stats.tex": render_stats(data),
        "tab-rule-summary.tex": render_rule_summary(data),
        "tab-precision.tex": render_precision_table(data),
        "tab-recall.tex": render_recall_table(data),
        "tab-catalogue.tex": render_catalogue_table(data),
        "tab-benchmark.tex": render_benchmark_table(data),
    }


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", delete=False, dir=path.parent, prefix=path.name + "."
    ) as tmp:
        tmp.write(content)
        name = tmp.name
    os.replace(name, path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m tools.generate_paper_stats")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--audit", action="store_true")
    args = parser.parse_args(argv)

    if args.audit:
        return audit_paper()

    data = collect()
    if data["nonr"]["unknown"]:
        print(
            "warning: github corpus rows with no language classification in "
            f"{NONR_SOURCES_MD.name}: {', '.join(data['nonr']['unknown'])}",
            file=sys.stderr,
        )
    rendered = render_all(data)

    if args.check:
        stale = [
            name
            for name, content in rendered.items()
            if not (OUTPUT_DIR / name).exists()
            or (OUTPUT_DIR / name).read_text(encoding="utf-8") != content
        ]
        if stale:
            print(
                "error: paper/generated/ is out of date: " + ", ".join(stale),
                file=sys.stderr,
            )
            return 1
        return 0

    for name, content in rendered.items():
        _atomic_write(OUTPUT_DIR / name, content)
        print(f"wrote paper/generated/{name}")
    return 0


if __name__ == "__main__":  # pragma: no cover — CLI entry point
    raise SystemExit(main())
