"""Render the JSS rule catalogue from YAML to Markdown.

Invoke from the repository root::

    python -m tools.render_catalogue          # write catalogue.md
    python -m tools.render_catalogue --check  # exit 1 if catalogue.md drifts

The source of truth is ``specs/003-jss-rule-catalogue/catalogue.yaml``.
The output ``specs/003-jss-rule-catalogue/catalogue.md`` is a generated
artefact; edits to it will be overwritten by the next render.

No templating engine — string concatenation against the fixed table
shape from ``contracts/rendering.md``.
"""

from __future__ import annotations

import argparse
import os
import sys
import tempfile
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

import yaml

from tools._catalogue_validate import (
    CatalogueError,
    validate,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
CATALOGUE_YAML = REPO_ROOT / "specs" / "003-jss-rule-catalogue" / "catalogue.yaml"
CATALOGUE_MD = REPO_ROOT / "specs" / "003-jss-rule-catalogue" / "catalogue.md"
TEMPLATE_DIR = REPO_ROOT / "docs" / "jss-template"


# ---------------------------------------------------------------------------
# Category titles — title-case of the id, with special cases
# ---------------------------------------------------------------------------

_TITLE_OVERRIDES: Mapping[str, str] = {
    "code_style": "Code style",
    "code_width": "Code width",
    "house_style": "House style",
    "crossrefs": "Cross-references",
    "bibtex": "BibTeX",
}


def _title(category: str) -> str:
    return _TITLE_OVERRIDES.get(category, category.capitalize())


# Per-category fence language for the rendered example blocks.
_BIB_CATEGORIES: frozenset[str] = frozenset({"references", "bibtex"})


def _fence_lang(category: str) -> str:
    return "bibtex" if category in _BIB_CATEGORIES else "latex"


# ---------------------------------------------------------------------------
# Sorting
# ---------------------------------------------------------------------------


def _rule_id_counter(rule_id: str) -> int:
    return int(rule_id.rsplit("-", 1)[-1])


def _sort_key(rule: Mapping[str, Any], category_order: Sequence[str]) -> tuple[int, int]:
    category = rule["category"]
    try:
        category_idx = category_order.index(category)
    except ValueError:
        category_idx = len(category_order)  # unknown categories sink to the end
    return (category_idx, _rule_id_counter(rule["rule_id"]))


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def render(doc: Mapping[str, Any]) -> str:
    """Render the validated catalogue doc as Markdown.

    Caller is expected to have already validated *doc* via
    :func:`tools._catalogue_validate.validate`. The renderer does no
    further validation — garbage in, garbage out (the CLI wrapper
    below refuses to call render on an invalid doc).
    """
    categories: list[str] = list(doc["categories"])
    rules: list[dict[str, Any]] = sorted(
        (dict(r) for r in doc["rules"]),
        key=lambda r: _sort_key(r, categories),
    )

    out: list[str] = []
    _emit_header(out, doc, rules, categories)

    # Group rules by category for the per-category sections
    by_category: dict[str, list[dict[str, Any]]] = {c: [] for c in categories}
    for rule in rules:
        by_category.setdefault(rule["category"], []).append(rule)

    for category in categories:
        category_rules = by_category.get(category, [])
        if not category_rules:
            continue  # validator already flags dangling categories
        _emit_category(out, category, category_rules)

    # Per-rule detail blocks — iterate the already-sorted list
    out.append("## Rule details\n\n")
    for rule in rules:
        _emit_rule_detail(out, rule)

    return "".join(out)


# ---------------------------------------------------------------------------
# Section emitters
# ---------------------------------------------------------------------------


def _emit_header(
    out: list[str],
    doc: Mapping[str, Any],
    rules: Sequence[Mapping[str, Any]],
    categories: Sequence[str],
) -> None:
    out.append("# JSS Rule Catalogue\n\n")
    out.append(
        "**Source of truth**: [catalogue.yaml](catalogue.yaml). "
        "This markdown is generated by `python -m tools.render_catalogue`; "
        "edits here are overwritten.\n\n"
    )
    out.append(f"**Schema version**: {doc['version']}  \n")
    out.append(
        f"**Vendored sources**: `docs/jss-template/jss.cls` dated "
        f"{doc['source_vendored_at']}  \n"
    )
    out.append(f"**Rule count**: {len(rules)}  \n")
    out.append(f"**Category count**: {len(categories)}\n\n")
    out.append("---\n\n")


def _emit_category(
    out: list[str],
    category: str,
    rules: Sequence[Mapping[str, Any]],
) -> None:
    out.append(f"## {_title(category)}\n\n")
    out.append(f"_{category}_ — {len(rules)} rule(s)\n\n")
    out.append(
        "| Rule ID | Severity | Description | Authority | Authority ref | Auto-fixable |\n"
    )
    out.append("|---|---|---|---|---|---|\n")
    for rule in rules:
        out.append(_render_summary_row(rule))
    out.append("\n")


def _render_summary_row(rule: Mapping[str, Any]) -> str:
    rule_id = rule["rule_id"]
    severity = rule["severity"]
    description = _escape_pipe(rule["description"])
    authority = rule["authority"]
    authority_ref = f"`{rule['authority_ref']}`"
    auto_fixable = "✓" if rule["auto_fixable"] else "—"
    return (
        f"| `{rule_id}` | {severity} | {description} | {authority} | "
        f"{authority_ref} | {auto_fixable} |\n"
    )


def _escape_pipe(text: str) -> str:
    # Markdown tables interpret '|' as column separator. The few rules that
    # contain '|' in their description (e.g., a LaTeX or-group reference)
    # need it escaped.
    return text.replace("|", r"\|")


def _emit_rule_detail(out: list[str], rule: Mapping[str, Any]) -> None:
    rule_id = rule["rule_id"]
    category = rule["category"]
    severity = rule["severity"]
    auto_fixable = "yes" if rule["auto_fixable"] else "no"
    description = rule["description"]
    authority = rule["authority"]
    authority_ref = rule["authority_ref"]
    inspects = ", ".join(f"`{x}`" for x in rule["inspects"])
    example_violation = _strip_trailing_newline(rule["example_violation"])
    example_fix = _strip_trailing_newline(rule["example_fix"])
    lang = _fence_lang(category)
    notes = rule.get("notes")

    out.append(f"### {rule_id}\n\n")
    out.append(
        f"**Category**: `{category}` · "
        f"**Severity**: `{severity}` · "
        f"**Auto-fixable**: {auto_fixable}\n\n"
    )
    out.append(f"{description}\n\n")
    out.append(f"**Authority**: `{authority}` → `{authority_ref}`\n\n")
    out.append(f"**Inspects**: {inspects}\n\n")
    out.append("<details>\n<summary>Example violation</summary>\n\n")
    out.append(f"```{lang}\n{example_violation}\n```\n\n")
    out.append("</details>\n\n")
    out.append("<details>\n<summary>Example fix</summary>\n\n")
    out.append(f"```{lang}\n{example_fix}\n```\n\n")
    out.append("</details>\n\n")
    if notes and str(notes).strip():
        out.append(f"**Notes**: {notes.strip()}\n\n")
    out.append("---\n\n")


def _strip_trailing_newline(text: str) -> str:
    # YAML's `|` block scalar adds one trailing newline; strip it so the
    # markdown fenced block doesn't pick up an empty last line.
    return text[:-1] if text.endswith("\n") else text


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _load_doc(path: Path) -> Mapping[str, Any]:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def _report_and_exit(errors: Sequence[CatalogueError]) -> None:
    print("catalogue.yaml is invalid:", file=sys.stderr)
    for err in errors:
        print(f"  {err}", file=sys.stderr)
    sys.exit(2)


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", delete=False, dir=path.parent, prefix=path.name + "."
    ) as tmp:
        tmp.write(content)
        tmp_name = tmp.name
    os.replace(tmp_name, path)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m tools.render_catalogue",
        description="Render catalogue.yaml into catalogue.md.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 0 if the committed markdown matches, 1 if it drifts",
    )
    parser.add_argument(
        "--yaml-path",
        type=Path,
        default=CATALOGUE_YAML,
        help="override the YAML input path (default: %(default)s)",
    )
    parser.add_argument(
        "--md-path",
        type=Path,
        default=CATALOGUE_MD,
        help="override the Markdown output path (default: %(default)s)",
    )
    parser.add_argument(
        "--template-dir",
        type=Path,
        default=TEMPLATE_DIR,
        help="override the vendored template dir used for authority-ref resolvability",
    )
    args = parser.parse_args(argv)

    if not args.yaml_path.exists():
        print(f"error: {args.yaml_path} does not exist", file=sys.stderr)
        return 2

    doc = _load_doc(args.yaml_path)
    errors = validate(doc, template_dir=args.template_dir)
    if errors:
        _report_and_exit(errors)

    rendered = render(doc)

    if args.check:
        if not args.md_path.exists():
            print(
                f"error: {args.md_path} does not exist; run without --check first",
                file=sys.stderr,
            )
            return 1
        committed = args.md_path.read_text(encoding="utf-8")
        if committed != rendered:
            print(
                f"error: {args.md_path} is out of date with {args.yaml_path}. "
                "Re-run without --check.",
                file=sys.stderr,
            )
            return 1
        return 0

    _atomic_write(args.md_path, rendered)
    print(f"wrote {args.md_path}")
    return 0


if __name__ == "__main__":  # pragma: no cover — CLI entry point
    raise SystemExit(main())
