#!/usr/bin/env bash
# Manuscript regeneration gate for "jss-lint" (JSS submission) — internal.
#
# Regenerates every statistic, table body, and terminal listing shown in
# the manuscript from the repository's pinned evaluation artifacts, then
# proves the manuscript itself complies with the style rules it describes
# (self-referential check) and rebuilds the PDF. Requires the full
# repository; the reviewer-facing replication script is replicate.sh.
#
# Usage:  bash regenerate.sh [--no-pdf]
#
# Requirements: Python >= 3.10 (the package is installed editable if not
# importable), Rscript with the jsslintr package, pdflatex + bibtex
# (unless --no-pdf), git.
set -euo pipefail
cd "$(dirname "$0")"
# Pin all terminal captures to UTF-8, independent of the caller's locale.
export PYTHONIOENCODING=utf-8
REPO_ROOT=$(cd .. && pwd)
NO_PDF=${1:-}

step() { printf '\n== %s\n' "$*"; }

# -- 0. toolchain -----------------------------------------------------------
PY=${JSS_PAPER_PYTHON:-}
if [ -z "$PY" ]; then
    for cand in "$REPO_ROOT/.venv-host/bin/python" python3; do
        if "$cand" -c 'import sys; sys.exit(sys.version_info < (3, 10))' \
            2>/dev/null; then PY=$cand; break; fi
    done
fi
[ -n "$PY" ] || { echo "error: need Python >= 3.10" >&2; exit 1; }
if ! "$PY" -c 'import texlint' 2>/dev/null; then
    step "installing texlint (editable) into $PY"
    "$PY" -m pip install --quiet -e "$REPO_ROOT[dev]"
fi
JSS_LINT() { "$PY" -m texlint.cli "$@"; }

# -- 1. version coherence ---------------------------------------------------
step "version coherence"
CLI_VERSION=$(JSS_LINT --version | sed 's/.*version //')
STAT_VERSION=$(sed -n 's/.*StatToolVersion}{\([^}]*\)}.*/\1/p' generated/stats.tex)
[ "$CLI_VERSION" = "$STAT_VERSION" ] || {
    echo "error: jss-lint $CLI_VERSION != stats.tex $STAT_VERSION" >&2; exit 1; }
echo "jss-lint $CLI_VERSION == generated/stats.tex"

# -- 2. statistics drift gate ----------------------------------------------
step "generated statistics match the pinned evaluation state"
(cd "$REPO_ROOT" && "$PY" -m tools.generate_paper_stats --check)

# -- 3. regenerate terminal listings ----------------------------------------
step "regenerating listings"
mkdir -p generated/listings
# 3a. reviewer-mode compliance summary on the intentionally non-compliant
#     demo, rendered as LaTeX table rows from the machine-readable JSON
#     output (the interactive terminal renderer draws the same data as a
#     Unicode table, which pdfLaTeX cannot embed verbatim).
(JSS_LINT --mode reviewer --output json examples/demo.tex || true) \
    | "$PY" -c '
import json, sys
doc = json.load(sys.stdin)
print("%% AUTO-GENERATED by regenerate.sh from"
      " `jss-lint --mode reviewer --output json examples/demo.tex`.")
for c in doc["categories"]:
    row = (c["title"], c["status"], c["rules_applied"], c["rules_passed"])
    print("{} & {} & {} & {} \\\\".format(*row))
print("\\midrule")
pct = doc["compliance_percentage"]
print("Overall compliance & \\multicolumn{3}{r}{" + format(pct, ".1f")
      + "\\%} \\\\")
print("\\bottomrule")
' > generated/tab-demo-reviewer.tex || {
        echo "error: reviewer JSON transform failed" >&2; exit 1; }
# 3b. auto-fix preview: unified-diff portion of --fix --dry-run.
# --no-resolve keeps the diff header at the literal "demo.tex": since
# multi-file auto-resolution shipped, a single-file invocation
# canonicalizes paths to absolute, which would bake the random mktemp
# directory into the listing and make this regeneration nondeterministic.
TMPDIR_FIX=$(mktemp -d)
cp examples/demo.tex "$TMPDIR_FIX/demo.tex"
(cd "$TMPDIR_FIX" && JSS_LINT --fix --dry-run --no-resolve demo.tex || true) \
    | awk '/^─/{exit} {print}' > generated/listings/demo-fix-diff.txt
rm -rf "$TMPDIR_FIX"
# 3c. rule documentation
JSS_LINT explain JSS-CITE-003 > generated/listings/explain-cite003.txt
# 3d. author-mode report on the demo, exactly as the terminal renderer
# prints it (fixed 120-column width, box-drawing rules), headed by the
# command line that produced it; exit 1 (violations found) is the
# expected outcome.
{
    echo '$ jss-lint examples/demo.tex'
    JSS_LINT examples/demo.tex || true
} > generated/listings/demo-lint.txt
# 3e. the R-channel session of §7, actually run: jsslint() discovers the
# demo in an otherwise empty directory, summary() prints the breakdown,
# jssfix(dry_run = TRUE) previews the diff. Assembled as a jss.cls
# CodeChunk. Requires Rscript with the jsslintr package installed.
Rscript -e 'quit(status = !requireNamespace("jsslintr", quietly = TRUE))' \
    2>/dev/null || {
        echo "error: Rscript with the jsslintr package is required" \
             "(install.packages(\"jsslintr\"))" >&2; exit 1; }
TMPDIR_R=$(mktemp -d)
cp examples/demo.tex "$TMPDIR_R/demo.tex"
(cd "$TMPDIR_R" && Rscript -e '
suppressMessages(library("jsslintr"))
res <- jsslint()
capture.output(summary(res), file = "summary.txt")
capture.output(invisible(jssfix("demo.tex", dry_run = TRUE)),
               file = "fixdiff.txt", type = "output")
')
{
    printf '%s\n' \
        "%% AUTO-GENERATED by regenerate.sh: the R session of Section 7," \
        "%% run by Rscript against examples/demo.tex in a scratch directory." \
        "\\begin{CodeChunk}" "\\begin{CodeInput}" \
        'R> library("jsslintr")' \
        'R> res <- jsslint()' \
        'R> summary(res)' \
        "\\end{CodeInput}" "\\begin{CodeOutput}"
    cat "$TMPDIR_R/summary.txt"
    printf '%s\n' "\\end{CodeOutput}" "\\begin{CodeInput}" \
        'R> jssfix("demo.tex", dry_run = TRUE)' \
        "\\end{CodeInput}" "\\begin{CodeOutput}"
    cat "$TMPDIR_R/fixdiff.txt"
    printf '%s\n' "\\end{CodeOutput}" "\\end{CodeChunk}"
} > generated/listings/r-session.tex
rm -rf "$TMPDIR_R"

# -- 4. committed artifacts == live tool output ------------------------------
step "committed generated/ matches live output"
git -C "$REPO_ROOT" diff --exit-code -- paper/generated || {
    echo "error: paper/generated/ differs from live regeneration" >&2; exit 1; }

# -- 5. the paper passes its own linter (hard gate) --------------------------
step "self-referential compliance check"
JSS_LINT paper.tex paper.bib
echo "paper.tex + paper.bib: no violations"

# -- 6. build the PDF ---------------------------------------------------------
if [ "$NO_PDF" != "--no-pdf" ]; then
    step "building paper.pdf"
    pdflatex -interaction=nonstopmode -halt-on-error paper.tex > /dev/null
    bibtex paper > /dev/null
    pdflatex -interaction=nonstopmode -halt-on-error paper.tex > /dev/null
    pdflatex -interaction=nonstopmode -halt-on-error paper.tex > /dev/null
    # Citation/reference warnings only: font-shape "undefined" warnings
    # depend on the local TeX installation, not the manuscript.
    if grep -E "Warning.*(Citation|Reference).*undefined" paper.log ; then
        echo "error: undefined citations/references" >&2; exit 1
    fi
    if command -v pdfinfo > /dev/null; then
        PAGES=$(pdfinfo paper.pdf | awk '/^Pages:/{print $2}')
    else
        PAGES=$(sed -n 's/.*Output written on paper\.pdf (\([0-9]*\) pages.*/\1/p' paper.log)
    fi
    echo "paper.pdf: $PAGES pages"
    [ "$PAGES" -le 34 ] || { echo "error: page budget exceeded" >&2; exit 1; }
fi

# -- 7. provenance ------------------------------------------------------------
step "provenance"
sed -n 's/\\newcommand{\\StatPinned\([A-Za-z]*\)}{\(.*\)}/  Pinned\1: \2/p' \
    generated/stats.tex
echo "regeneration complete."
