#!/usr/bin/env bash
# Replication script for "jss-lint" (JSS submission).
#
# Regenerates every statistic, table body, and terminal listing shown in
# the manuscript from the repository's pinned evaluation artifacts, then
# proves the manuscript itself complies with the style rules it describes
# (self-referential check) and rebuilds the PDF.
#
# Usage:  bash replicate.sh [--no-pdf]
#
# Requirements: Python >= 3.10 (the package is installed editable if not
# importable), pdflatex + bibtex (unless --no-pdf), git.
set -euo pipefail
cd "$(dirname "$0")"
REPO_ROOT=$(cd .. && pwd)
NO_PDF=${1:-}

step() { printf '\n== %s\n' "$*"; }

# -- 0. toolchain -----------------------------------------------------------
PY=${JSS_PAPER_PYTHON:-}
if [ -z "$PY" ]; then
    for cand in "$REPO_ROOT/.venv-host/bin/python" python3; do
        if "$cand" -c 'import sys; sys.exit(sys.version_info < (3, 10))' \
            2>/dev/null; then PY=$cand; break; fi
    done
fi
[ -n "$PY" ] || { echo "error: need Python >= 3.10" >&2; exit 1; }
if ! "$PY" -c 'import texlint' 2>/dev/null; then
    step "installing texlint (editable) into $PY"
    "$PY" -m pip install --quiet -e "$REPO_ROOT[dev]"
fi
JSS_LINT() { "$PY" -m texlint.cli "$@"; }

# -- 1. version coherence ---------------------------------------------------
step "version coherence"
CLI_VERSION=$(JSS_LINT --version | sed 's/.*version //')
STAT_VERSION=$(sed -n 's/.*StatToolVersion}{\([^}]*\)}.*/\1/p' generated/stats.tex)
[ "$CLI_VERSION" = "$STAT_VERSION" ] || {
    echo "error: jss-lint $CLI_VERSION != stats.tex $STAT_VERSION" >&2; exit 1; }
echo "jss-lint $CLI_VERSION == generated/stats.tex"

# -- 2. statistics drift gate ----------------------------------------------
step "generated statistics match the pinned evaluation state"
(cd "$REPO_ROOT" && "$PY" -m tools.generate_paper_stats --check)

# -- 3. regenerate terminal listings ----------------------------------------
step "regenerating listings"
mkdir -p generated/listings
# 3a. reviewer-mode compliance summary on the intentionally non-compliant
#     demo, rendered as LaTeX table rows from the machine-readable JSON
#     output (the interactive terminal renderer draws the same data as a
#     Unicode table, which pdfLaTeX cannot embed verbatim).
(JSS_LINT --mode reviewer --output json examples/demo.tex || true) \
    | "$PY" -c '
import json, sys
doc = json.load(sys.stdin)
print("%% AUTO-GENERATED by replicate.sh from"
      " `jss-lint --mode reviewer --output json examples/demo.tex`.")
for c in doc["categories"]:
    row = (c["title"], c["status"], c["rules_applied"], c["rules_passed"])
    print("{} & {} & {} & {} \\\\".format(*row))
print("\\midrule")
pct = doc["compliance_percentage"]
print("Overall compliance & \\multicolumn{3}{r}{" + format(pct, ".1f")
      + "\\%} \\\\")
print("\\bottomrule")
' > generated/tab-demo-reviewer.tex || {
        echo "error: reviewer JSON transform failed" >&2; exit 1; }
# 3b. auto-fix preview: unified-diff portion of --fix --dry-run
TMPDIR_FIX=$(mktemp -d)
cp examples/demo.tex "$TMPDIR_FIX/demo.tex"
(cd "$TMPDIR_FIX" && JSS_LINT --fix --dry-run demo.tex || true) \
    | awk '/^─/{exit} {print}' > generated/listings/demo-fix-diff.txt
rm -rf "$TMPDIR_FIX"
# 3c. rule documentation
JSS_LINT explain JSS-CITE-003 > generated/listings/explain-cite003.txt

# -- 4. committed artifacts == live tool output ------------------------------
step "committed generated/ matches live output"
git -C "$REPO_ROOT" diff --exit-code -- paper/generated || {
    echo "error: paper/generated/ differs from live regeneration" >&2; exit 1; }

# -- 5. the paper passes its own linter (hard gate) --------------------------
step "self-referential compliance check"
JSS_LINT paper.tex paper.bib
echo "paper.tex + paper.bib: no violations"

# -- 6. build the PDF ---------------------------------------------------------
if [ "$NO_PDF" != "--no-pdf" ]; then
    step "building paper.pdf"
    pdflatex -interaction=nonstopmode -halt-on-error paper.tex > /dev/null
    bibtex paper > /dev/null
    pdflatex -interaction=nonstopmode -halt-on-error paper.tex > /dev/null
    pdflatex -interaction=nonstopmode -halt-on-error paper.tex > /dev/null
    if grep -E "Warning.*undefined" paper.log | grep -Ev "^$" ; then
        echo "error: undefined citations/references" >&2; exit 1
    fi
    PAGES=$(pdfinfo paper.pdf | awk '/^Pages:/{print $2}')
    echo "paper.pdf: $PAGES pages"
    [ "$PAGES" -le 34 ] || { echo "error: page budget exceeded" >&2; exit 1; }
fi

# -- 7. provenance ------------------------------------------------------------
step "provenance"
sed -n 's/\\newcommand{\\StatPinned\([A-Za-z]*\)}{\(.*\)}/  Pinned\1: \2/p' \
    generated/stats.tex
echo "replication complete."
