#!/usr/bin/env python3
"""Regenerate inst/AUTHORS from the vendored crate archive.

CRAN's "Using Rust in CRAN packages" note and the Repository Policy require
the authorship and copyright of every bundled Rust crate to be declared:
DESCRIPTION carries a blanket `cph` person plus a Copyright field, and both
point at inst/AUTHORS for the actual list. This script derives that list
from src/rust/vendor.tar.xz itself — the same archive the offline build
compiles — so the credits cannot drift from what actually ships. Invoked at
the end of tools/vendor-crate-archive.sh; never runs at install time.
"""

from __future__ import annotations

import tarfile
import tomllib
from pathlib import Path

PKG_DIR = Path(__file__).resolve().parents[1]
VENDOR_ARCHIVE = PKG_DIR / "src/rust/vendor.tar.xz"
AUTHORS_FILE = PKG_DIR / "inst/AUTHORS"

HEADER = """\
Vendored Rust crates
====================

The jsslintr package embeds its Rust dependency crates (produced by
`cargo vendor`, shipped as src/rust/vendor.tar.xz and compiled during
package installation). The copyright of each crate remains with its
authors, listed below. The full license text and any additional
copyright notices of every crate ship inside the archive under
vendor/<crate>/. src/rust/jsslint-core is first-party code by the
package author, not a third-party dependency.

This file is generated by tools/generate-rust-authors.py — do not edit
by hand; rerun tools/vendor-crate-archive.sh instead.
"""


def main() -> None:
    crates = []
    with tarfile.open(VENDOR_ARCHIVE) as tf:
        for member in tf.getmembers():
            parts = member.name.split("/")
            if len(parts) == 3 and parts[0] == "vendor" and parts[2] == "Cargo.toml":
                fh = tf.extractfile(member)
                assert fh is not None
                pkg = tomllib.load(fh).get("package", {})
                crates.append(pkg)
    crates.sort(key=lambda p: p.get("name", ""))
    if not crates:
        raise SystemExit(f"generate-rust-authors: no crates found in {VENDOR_ARCHIVE}")

    lines = [HEADER]
    for pkg in crates:
        lines.append(f"{pkg['name']} {pkg['version']}")
        lines.append(f"  License: {pkg.get('license', 'see crate')}")
        authors = pkg.get("authors")
        if authors:
            lines.append(f"  Authors: {', '.join(authors)}")
        repo = pkg.get("repository")
        if repo:
            lines.append(f"  Repository: {repo}")
        lines.append("")

    AUTHORS_FILE.parent.mkdir(parents=True, exist_ok=True)
    AUTHORS_FILE.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {AUTHORS_FILE.relative_to(PKG_DIR)} ({len(crates)} crates)")


if __name__ == "__main__":
    main()
